







set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[0]}]


create_clock -period 10.000 -name sysclk_p -waveform {0.000 5.000} [get_ports i_sys_clk_p]
set_property PACKAGE_PIN D9 [get_ports i_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL135 [get_ports i_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL135 [get_ports i_sys_clk_n]


set_property IOSTANDARD LVCMOS33 [get_ports o_adc0_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc0_clkb]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SDI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SDO]
set_property PACKAGE_PIN AD18 [get_ports SPI_CS]
set_property PACKAGE_PIN AC19 [get_ports SPI_SCLK]
set_property PACKAGE_PIN AD19 [get_ports SPI_SDI]
set_property PACKAGE_PIN AC18 [get_ports SPI_SDO]

set_property PACKAGE_PIN AK22 [get_ports o_adc0_clka]
set_property PACKAGE_PIN AJ25 [get_ports o_adc0_clkb]
set_property PACKAGE_PIN AD21 [get_ports {i_adc0_data0[0]}]
set_property PACKAGE_PIN AC23 [get_ports {i_adc0_data0[1]}]
set_property PACKAGE_PIN AC22 [get_ports {i_adc0_data0[2]}]
set_property PACKAGE_PIN AG25 [get_ports {i_adc0_data0[3]}]
set_property PACKAGE_PIN AG24 [get_ports {i_adc0_data0[4]}]
set_property PACKAGE_PIN AF24 [get_ports {i_adc0_data0[5]}]
set_property PACKAGE_PIN AF23 [get_ports {i_adc0_data0[6]}]
set_property PACKAGE_PIN AE23 [get_ports {i_adc0_data0[7]}]
set_property PACKAGE_PIN AD23 [get_ports {i_adc0_data0[8]}]
set_property PACKAGE_PIN AD24 [get_ports {i_adc0_data0[9]}]
set_property PACKAGE_PIN AC24 [get_ports {i_adc0_data0[10]}]
set_property PACKAGE_PIN AK23 [get_ports {i_adc0_data0[11]}]
set_property PACKAGE_PIN AH19 [get_ports {i_adc0_data1[0]}]
set_property PACKAGE_PIN AK18 [get_ports {i_adc0_data1[1]}]
set_property PACKAGE_PIN AK17 [get_ports {i_adc0_data1[2]}]
set_property PACKAGE_PIN AH21 [get_ports {i_adc0_data1[3]}]
set_property PACKAGE_PIN AG21 [get_ports {i_adc0_data1[4]}]
set_property PACKAGE_PIN AH22 [get_ports {i_adc0_data1[5]}]
set_property PACKAGE_PIN AG22 [get_ports {i_adc0_data1[6]}]
set_property PACKAGE_PIN AH24 [get_ports {i_adc0_data1[7]}]
set_property PACKAGE_PIN AH23 [get_ports {i_adc0_data1[8]}]
set_property PACKAGE_PIN AJ24 [get_ports {i_adc0_data1[9]}]
set_property PACKAGE_PIN AJ23 [get_ports {i_adc0_data1[10]}]
set_property PACKAGE_PIN AK25 [get_ports {i_adc0_data1[11]}]

set_property PACKAGE_PIN P23 [get_ports {MOTO_DIR[0]}]
set_property PACKAGE_PIN P24 [get_ports {MOTO_PWM[0]}]
set_property PACKAGE_PIN R22 [get_ports {MOTO_DIR[1]}]
set_property PACKAGE_PIN R23 [get_ports {MOTO_PWM[1]}]
set_property PACKAGE_PIN T22 [get_ports {MOTO_DIR[2]}]
set_property PACKAGE_PIN T23 [get_ports {MOTO_PWM[2]}]
set_property PACKAGE_PIN P25 [get_ports {MOTO_DIR[3]}]
set_property PACKAGE_PIN P26 [get_ports {MOTO_PWM[3]}]
set_property PACKAGE_PIN U25 [get_ports {MOTO_DIR[4]}]
set_property PACKAGE_PIN V26 [get_ports {MOTO_PWM[4]}]
set_property PACKAGE_PIN V23 [get_ports {MOTO_DIR[5]}]
set_property PACKAGE_PIN W24 [get_ports {MOTO_PWM[5]}]
set_property PACKAGE_PIN W25 [get_ports {MOTO_DIR[6]}]
set_property PACKAGE_PIN W26 [get_ports {MOTO_PWM[6]}]
set_property PACKAGE_PIN P21 [get_ports {MOTO_DIR[7]}]
set_property PACKAGE_PIN R21 [get_ports {MOTO_PWM[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[0]}]

set_property PACKAGE_PIN T28 [get_ports {MOTO_EN[0]}]
set_property PACKAGE_PIN P28 [get_ports {MOTO_EN[1]}]
set_property PACKAGE_PIN U30 [get_ports {MOTO_EN[2]}]
set_property PACKAGE_PIN N27 [get_ports {MOTO_EN[3]}]
set_property PACKAGE_PIN R30 [get_ports {MOTO_EN[4]}]
set_property PACKAGE_PIN P29 [get_ports {MOTO_EN[5]}]
set_property PACKAGE_PIN R26 [get_ports {MOTO_EN[6]}]
set_property PACKAGE_PIN V24 [get_ports {MOTO_EN[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[7]}]

set_property PACKAGE_PIN R28 [get_ports {MOTO_ALM[0]}]
set_property PACKAGE_PIN N28 [get_ports {MOTO_ALM[1]}]
set_property PACKAGE_PIN T30 [get_ports {MOTO_ALM[2]}]
set_property PACKAGE_PIN N26 [get_ports {MOTO_ALM[3]}]
set_property PACKAGE_PIN P30 [get_ports {MOTO_ALM[4]}]
set_property PACKAGE_PIN N29 [get_ports {MOTO_ALM[5]}]
set_property PACKAGE_PIN R25 [get_ports {MOTO_ALM[6]}]
set_property PACKAGE_PIN U24 [get_ports {MOTO_ALM[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[0]}]

set_property PACKAGE_PIN AG17 [get_ports {debug_led[0]}]
set_property PACKAGE_PIN AG16 [get_ports {debug_led[1]}]
set_property PACKAGE_PIN AF15 [get_ports {debug_led[2]}]
set_property PACKAGE_PIN AG15 [get_ports {debug_led[3]}]
set_property PACKAGE_PIN AF14 [get_ports {debug_led[4]}]
set_property PACKAGE_PIN AG14 [get_ports {debug_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[0]}]










set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[0]}]
set_property PACKAGE_PIN AJ21 [get_ports {i_adc3_data0[11]}]
set_property PACKAGE_PIN AK21 [get_ports {i_adc3_data0[10]}]
set_property PACKAGE_PIN AJ20 [get_ports {i_adc3_data0[9]}]
set_property PACKAGE_PIN AK20 [get_ports {i_adc3_data0[8]}]
set_property PACKAGE_PIN AF20 [get_ports {i_adc3_data0[7]}]
set_property PACKAGE_PIN AG20 [get_ports {i_adc3_data0[6]}]
set_property PACKAGE_PIN AA22 [get_ports {i_adc3_data0[5]}]
set_property PACKAGE_PIN AA23 [get_ports {i_adc3_data0[4]}]
set_property PACKAGE_PIN AB21 [get_ports {i_adc3_data0[3]}]
set_property PACKAGE_PIN AB22 [get_ports {i_adc3_data0[2]}]
set_property PACKAGE_PIN AD20 [get_ports {i_adc3_data0[1]}]
set_property PACKAGE_PIN AE20 [get_ports {i_adc3_data0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[0]}]
set_property PACKAGE_PIN AA24 [get_ports {i_adc3_data1[11]}]
set_property PACKAGE_PIN AB24 [get_ports {i_adc3_data1[10]}]
set_property PACKAGE_PIN Y22 [get_ports {i_adc3_data1[9]}]
set_property PACKAGE_PIN Y23 [get_ports {i_adc3_data1[8]}]
set_property PACKAGE_PIN W21 [get_ports {i_adc3_data1[7]}]
set_property PACKAGE_PIN Y21 [get_ports {i_adc3_data1[6]}]
set_property PACKAGE_PIN AF19 [get_ports {i_adc3_data1[5]}]
set_property PACKAGE_PIN AG19 [get_ports {i_adc3_data1[4]}]
set_property PACKAGE_PIN Y20 [get_ports {i_adc3_data1[3]}]
set_property PACKAGE_PIN AA20 [get_ports {i_adc3_data1[2]}]
set_property PACKAGE_PIN AB19 [get_ports {i_adc3_data1[1]}]
set_property PACKAGE_PIN AB20 [get_ports {i_adc3_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[0]}]
set_property PACKAGE_PIN AB16 [get_ports {i_adc4_data0[11]}]
set_property PACKAGE_PIN AC17 [get_ports {i_adc4_data0[10]}]
set_property PACKAGE_PIN AC16 [get_ports {i_adc4_data0[9]}]
set_property PACKAGE_PIN AA15 [get_ports {i_adc4_data0[8]}]
set_property PACKAGE_PIN AA14 [get_ports {i_adc4_data0[7]}]
set_property PACKAGE_PIN AB15 [get_ports {i_adc4_data0[6]}]
set_property PACKAGE_PIN AB14 [get_ports {i_adc4_data0[5]}]
set_property PACKAGE_PIN AC14 [get_ports {i_adc4_data0[4]}]
set_property PACKAGE_PIN AC13 [get_ports {i_adc4_data0[3]}]
set_property PACKAGE_PIN AB12 [get_ports {i_adc4_data0[2]}]
set_property PACKAGE_PIN AC12 [get_ports {i_adc4_data0[1]}]
set_property PACKAGE_PIN AH18 [get_ports {i_adc4_data0[0]}]
set_property PACKAGE_PIN AE17 [get_ports {i_adc4_data1[11]}]
set_property PACKAGE_PIN AD16 [get_ports {i_adc4_data1[10]}]
set_property PACKAGE_PIN AD15 [get_ports {i_adc4_data1[9]}]
set_property PACKAGE_PIN AE16 [get_ports {i_adc4_data1[8]}]
set_property PACKAGE_PIN AE15 [get_ports {i_adc4_data1[7]}]
set_property PACKAGE_PIN AD14 [get_ports {i_adc4_data1[6]}]
set_property PACKAGE_PIN AD13 [get_ports {i_adc4_data1[5]}]
set_property PACKAGE_PIN AE13 [get_ports {i_adc4_data1[4]}]
set_property PACKAGE_PIN AF13 [get_ports {i_adc4_data1[3]}]
set_property PACKAGE_PIN AE12 [get_ports {i_adc4_data1[2]}]
set_property PACKAGE_PIN AF12 [get_ports {i_adc4_data1[1]}]
set_property PACKAGE_PIN AJ16 [get_ports {i_adc4_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc3_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc3_clkb]
set_property PACKAGE_PIN AE22 [get_ports o_adc3_clka]
set_property PACKAGE_PIN AF22 [get_ports o_adc3_clkb]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc4_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc4_clkb]
set_property PACKAGE_PIN AB17 [get_ports o_adc4_clka]
set_property PACKAGE_PIN AE18 [get_ports o_adc4_clkb]














set_property PACKAGE_PIN AD28 [get_ports {i_adc1_data0[11]}]
set_property PACKAGE_PIN AD25 [get_ports {i_adc1_data0[10]}]
set_property PACKAGE_PIN AE26 [get_ports {i_adc1_data0[9]}]
set_property PACKAGE_PIN AE25 [get_ports {i_adc1_data0[8]}]
set_property PACKAGE_PIN AF25 [get_ports {i_adc1_data0[7]}]
set_property PACKAGE_PIN AG26 [get_ports {i_adc1_data0[6]}]
set_property PACKAGE_PIN AG27 [get_ports {i_adc1_data0[5]}]
set_property PACKAGE_PIN AH26 [get_ports {i_adc1_data0[4]}]
set_property PACKAGE_PIN AH27 [get_ports {i_adc1_data0[3]}]
set_property PACKAGE_PIN AJ26 [get_ports {i_adc1_data0[2]}]
set_property PACKAGE_PIN AK26 [get_ports {i_adc1_data0[1]}]
set_property PACKAGE_PIN AK27 [get_ports {i_adc1_data0[0]}]
set_property PACKAGE_PIN AF28 [get_ports {i_adc1_data1[11]}]
set_property PACKAGE_PIN AD30 [get_ports {i_adc1_data1[10]}]
set_property PACKAGE_PIN AE30 [get_ports {i_adc1_data1[9]}]
set_property PACKAGE_PIN AF30 [get_ports {i_adc1_data1[8]}]
set_property PACKAGE_PIN AG30 [get_ports {i_adc1_data1[7]}]
set_property PACKAGE_PIN AF29 [get_ports {i_adc1_data1[6]}]
set_property PACKAGE_PIN AG29 [get_ports {i_adc1_data1[5]}]
set_property PACKAGE_PIN AH28 [get_ports {i_adc1_data1[4]}]
set_property PACKAGE_PIN AH29 [get_ports {i_adc1_data1[3]}]
set_property PACKAGE_PIN AJ28 [get_ports {i_adc1_data1[2]}]
set_property PACKAGE_PIN AJ29 [get_ports {i_adc1_data1[1]}]
set_property PACKAGE_PIN AJ30 [get_ports {i_adc1_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc1_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc1_clkb]
set_property PACKAGE_PIN AC28 [get_ports o_adc1_clka]
set_property PACKAGE_PIN AE28 [get_ports o_adc1_clkb]



set_property IOSTANDARD LVCMOS33 [get_ports FPGA_T25]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_T24]
set_property PACKAGE_PIN T24 [get_ports FPGA_T24]
set_property PACKAGE_PIN T25 [get_ports FPGA_T25]








connect_debug_port u_ila_1/probe0 [get_nets [list {DiCoupler_top/adc1_ch3_lpf_400k_data[0]} {DiCoupler_top/adc1_ch3_lpf_400k_data[1]} {DiCoupler_top/adc1_ch3_lpf_400k_data[2]} {DiCoupler_top/adc1_ch3_lpf_400k_data[3]} {DiCoupler_top/adc1_ch3_lpf_400k_data[4]} {DiCoupler_top/adc1_ch3_lpf_400k_data[5]} {DiCoupler_top/adc1_ch3_lpf_400k_data[6]} {DiCoupler_top/adc1_ch3_lpf_400k_data[7]} {DiCoupler_top/adc1_ch3_lpf_400k_data[8]} {DiCoupler_top/adc1_ch3_lpf_400k_data[9]} {DiCoupler_top/adc1_ch3_lpf_400k_data[10]} {DiCoupler_top/adc1_ch3_lpf_400k_data[11]} {DiCoupler_top/adc1_ch3_lpf_400k_data[12]} {DiCoupler_top/adc1_ch3_lpf_400k_data[13]} {DiCoupler_top/adc1_ch3_lpf_400k_data[14]} {DiCoupler_top/adc1_ch3_lpf_400k_data[15]} {DiCoupler_top/adc1_ch3_lpf_400k_data[16]} {DiCoupler_top/adc1_ch3_lpf_400k_data[17]} {DiCoupler_top/adc1_ch3_lpf_400k_data[18]} {DiCoupler_top/adc1_ch3_lpf_400k_data[19]} {DiCoupler_top/adc1_ch3_lpf_400k_data[20]} {DiCoupler_top/adc1_ch3_lpf_400k_data[21]} {DiCoupler_top/adc1_ch3_lpf_400k_data[22]} {DiCoupler_top/adc1_ch3_lpf_400k_data[23]} {DiCoupler_top/adc1_ch3_lpf_400k_data[24]} {DiCoupler_top/adc1_ch3_lpf_400k_data[25]} {DiCoupler_top/adc1_ch3_lpf_400k_data[26]} {DiCoupler_top/adc1_ch3_lpf_400k_data[27]} {DiCoupler_top/adc1_ch3_lpf_400k_data[28]} {DiCoupler_top/adc1_ch3_lpf_400k_data[29]} {DiCoupler_top/adc1_ch3_lpf_400k_data[30]} {DiCoupler_top/adc1_ch3_lpf_400k_data[31]} {DiCoupler_top/adc1_ch3_lpf_400k_data[32]} {DiCoupler_top/adc1_ch3_lpf_400k_data[33]} {DiCoupler_top/adc1_ch3_lpf_400k_data[34]} {DiCoupler_top/adc1_ch3_lpf_400k_data[35]} {DiCoupler_top/adc1_ch3_lpf_400k_data[36]} {DiCoupler_top/adc1_ch3_lpf_400k_data[37]} {DiCoupler_top/adc1_ch3_lpf_400k_data[38]} {DiCoupler_top/adc1_ch3_lpf_400k_data[39]} {DiCoupler_top/adc1_ch3_lpf_400k_data[40]} {DiCoupler_top/adc1_ch3_lpf_400k_data[41]} {DiCoupler_top/adc1_ch3_lpf_400k_data[42]} {DiCoupler_top/adc1_ch3_lpf_400k_data[43]} {DiCoupler_top/adc1_ch3_lpf_400k_data[44]} {DiCoupler_top/adc1_ch3_lpf_400k_data[45]} {DiCoupler_top/adc1_ch3_lpf_400k_data[46]} {DiCoupler_top/adc1_ch3_lpf_400k_data[47]} {DiCoupler_top/adc1_ch3_lpf_400k_data[48]} {DiCoupler_top/adc1_ch3_lpf_400k_data[49]} {DiCoupler_top/adc1_ch3_lpf_400k_data[50]} {DiCoupler_top/adc1_ch3_lpf_400k_data[51]} {DiCoupler_top/adc1_ch3_lpf_400k_data[52]} {DiCoupler_top/adc1_ch3_lpf_400k_data[53]} {DiCoupler_top/adc1_ch3_lpf_400k_data[54]} {DiCoupler_top/adc1_ch3_lpf_400k_data[55]} {DiCoupler_top/adc1_ch3_lpf_400k_data[56]} {DiCoupler_top/adc1_ch3_lpf_400k_data[57]} {DiCoupler_top/adc1_ch3_lpf_400k_data[58]} {DiCoupler_top/adc1_ch3_lpf_400k_data[59]} {DiCoupler_top/adc1_ch3_lpf_400k_data[60]} {DiCoupler_top/adc1_ch3_lpf_400k_data[61]} {DiCoupler_top/adc1_ch3_lpf_400k_data[62]} {DiCoupler_top/adc1_ch3_lpf_400k_data[63]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {DiCoupler_top/adc1_ch3_lpf_data[0]} {DiCoupler_top/adc1_ch3_lpf_data[1]} {DiCoupler_top/adc1_ch3_lpf_data[2]} {DiCoupler_top/adc1_ch3_lpf_data[3]} {DiCoupler_top/adc1_ch3_lpf_data[4]} {DiCoupler_top/adc1_ch3_lpf_data[5]} {DiCoupler_top/adc1_ch3_lpf_data[6]} {DiCoupler_top/adc1_ch3_lpf_data[7]} {DiCoupler_top/adc1_ch3_lpf_data[8]} {DiCoupler_top/adc1_ch3_lpf_data[9]} {DiCoupler_top/adc1_ch3_lpf_data[10]} {DiCoupler_top/adc1_ch3_lpf_data[11]} {DiCoupler_top/adc1_ch3_lpf_data[12]} {DiCoupler_top/adc1_ch3_lpf_data[13]} {DiCoupler_top/adc1_ch3_lpf_data[14]} {DiCoupler_top/adc1_ch3_lpf_data[15]} {DiCoupler_top/adc1_ch3_lpf_data[16]} {DiCoupler_top/adc1_ch3_lpf_data[17]} {DiCoupler_top/adc1_ch3_lpf_data[18]} {DiCoupler_top/adc1_ch3_lpf_data[19]} {DiCoupler_top/adc1_ch3_lpf_data[20]} {DiCoupler_top/adc1_ch3_lpf_data[21]} {DiCoupler_top/adc1_ch3_lpf_data[22]} {DiCoupler_top/adc1_ch3_lpf_data[23]} {DiCoupler_top/adc1_ch3_lpf_data[24]} {DiCoupler_top/adc1_ch3_lpf_data[25]} {DiCoupler_top/adc1_ch3_lpf_data[26]} {DiCoupler_top/adc1_ch3_lpf_data[27]} {DiCoupler_top/adc1_ch3_lpf_data[28]} {DiCoupler_top/adc1_ch3_lpf_data[29]} {DiCoupler_top/adc1_ch3_lpf_data[30]} {DiCoupler_top/adc1_ch3_lpf_data[31]} {DiCoupler_top/adc1_ch3_lpf_data[32]} {DiCoupler_top/adc1_ch3_lpf_data[33]} {DiCoupler_top/adc1_ch3_lpf_data[34]} {DiCoupler_top/adc1_ch3_lpf_data[35]} {DiCoupler_top/adc1_ch3_lpf_data[36]} {DiCoupler_top/adc1_ch3_lpf_data[37]} {DiCoupler_top/adc1_ch3_lpf_data[38]} {DiCoupler_top/adc1_ch3_lpf_data[39]} {DiCoupler_top/adc1_ch3_lpf_data[40]} {DiCoupler_top/adc1_ch3_lpf_data[41]} {DiCoupler_top/adc1_ch3_lpf_data[42]} {DiCoupler_top/adc1_ch3_lpf_data[43]} {DiCoupler_top/adc1_ch3_lpf_data[44]} {DiCoupler_top/adc1_ch3_lpf_data[45]} {DiCoupler_top/adc1_ch3_lpf_data[46]} {DiCoupler_top/adc1_ch3_lpf_data[47]} {DiCoupler_top/adc1_ch3_lpf_data[48]} {DiCoupler_top/adc1_ch3_lpf_data[49]} {DiCoupler_top/adc1_ch3_lpf_data[50]} {DiCoupler_top/adc1_ch3_lpf_data[51]} {DiCoupler_top/adc1_ch3_lpf_data[52]} {DiCoupler_top/adc1_ch3_lpf_data[53]} {DiCoupler_top/adc1_ch3_lpf_data[54]} {DiCoupler_top/adc1_ch3_lpf_data[55]} {DiCoupler_top/adc1_ch3_lpf_data[56]} {DiCoupler_top/adc1_ch3_lpf_data[57]} {DiCoupler_top/adc1_ch3_lpf_data[58]} {DiCoupler_top/adc1_ch3_lpf_data[59]} {DiCoupler_top/adc1_ch3_lpf_data[60]} {DiCoupler_top/adc1_ch3_lpf_data[61]} {DiCoupler_top/adc1_ch3_lpf_data[62]} {DiCoupler_top/adc1_ch3_lpf_data[63]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list {DiCoupler_top/adc0_ch3_lpf_400k_data[0]} {DiCoupler_top/adc0_ch3_lpf_400k_data[1]} {DiCoupler_top/adc0_ch3_lpf_400k_data[2]} {DiCoupler_top/adc0_ch3_lpf_400k_data[3]} {DiCoupler_top/adc0_ch3_lpf_400k_data[4]} {DiCoupler_top/adc0_ch3_lpf_400k_data[5]} {DiCoupler_top/adc0_ch3_lpf_400k_data[6]} {DiCoupler_top/adc0_ch3_lpf_400k_data[7]} {DiCoupler_top/adc0_ch3_lpf_400k_data[8]} {DiCoupler_top/adc0_ch3_lpf_400k_data[9]} {DiCoupler_top/adc0_ch3_lpf_400k_data[10]} {DiCoupler_top/adc0_ch3_lpf_400k_data[11]} {DiCoupler_top/adc0_ch3_lpf_400k_data[12]} {DiCoupler_top/adc0_ch3_lpf_400k_data[13]} {DiCoupler_top/adc0_ch3_lpf_400k_data[14]} {DiCoupler_top/adc0_ch3_lpf_400k_data[15]} {DiCoupler_top/adc0_ch3_lpf_400k_data[16]} {DiCoupler_top/adc0_ch3_lpf_400k_data[17]} {DiCoupler_top/adc0_ch3_lpf_400k_data[18]} {DiCoupler_top/adc0_ch3_lpf_400k_data[19]} {DiCoupler_top/adc0_ch3_lpf_400k_data[20]} {DiCoupler_top/adc0_ch3_lpf_400k_data[21]} {DiCoupler_top/adc0_ch3_lpf_400k_data[22]} {DiCoupler_top/adc0_ch3_lpf_400k_data[23]} {DiCoupler_top/adc0_ch3_lpf_400k_data[24]} {DiCoupler_top/adc0_ch3_lpf_400k_data[25]} {DiCoupler_top/adc0_ch3_lpf_400k_data[26]} {DiCoupler_top/adc0_ch3_lpf_400k_data[27]} {DiCoupler_top/adc0_ch3_lpf_400k_data[28]} {DiCoupler_top/adc0_ch3_lpf_400k_data[29]} {DiCoupler_top/adc0_ch3_lpf_400k_data[30]} {DiCoupler_top/adc0_ch3_lpf_400k_data[31]} {DiCoupler_top/adc0_ch3_lpf_400k_data[32]} {DiCoupler_top/adc0_ch3_lpf_400k_data[33]} {DiCoupler_top/adc0_ch3_lpf_400k_data[34]} {DiCoupler_top/adc0_ch3_lpf_400k_data[35]} {DiCoupler_top/adc0_ch3_lpf_400k_data[36]} {DiCoupler_top/adc0_ch3_lpf_400k_data[37]} {DiCoupler_top/adc0_ch3_lpf_400k_data[38]} {DiCoupler_top/adc0_ch3_lpf_400k_data[39]} {DiCoupler_top/adc0_ch3_lpf_400k_data[40]} {DiCoupler_top/adc0_ch3_lpf_400k_data[41]} {DiCoupler_top/adc0_ch3_lpf_400k_data[42]} {DiCoupler_top/adc0_ch3_lpf_400k_data[43]} {DiCoupler_top/adc0_ch3_lpf_400k_data[44]} {DiCoupler_top/adc0_ch3_lpf_400k_data[45]} {DiCoupler_top/adc0_ch3_lpf_400k_data[46]} {DiCoupler_top/adc0_ch3_lpf_400k_data[47]} {DiCoupler_top/adc0_ch3_lpf_400k_data[48]} {DiCoupler_top/adc0_ch3_lpf_400k_data[49]} {DiCoupler_top/adc0_ch3_lpf_400k_data[50]} {DiCoupler_top/adc0_ch3_lpf_400k_data[51]} {DiCoupler_top/adc0_ch3_lpf_400k_data[52]} {DiCoupler_top/adc0_ch3_lpf_400k_data[53]} {DiCoupler_top/adc0_ch3_lpf_400k_data[54]} {DiCoupler_top/adc0_ch3_lpf_400k_data[55]} {DiCoupler_top/adc0_ch3_lpf_400k_data[56]} {DiCoupler_top/adc0_ch3_lpf_400k_data[57]} {DiCoupler_top/adc0_ch3_lpf_400k_data[58]} {DiCoupler_top/adc0_ch3_lpf_400k_data[59]} {DiCoupler_top/adc0_ch3_lpf_400k_data[60]} {DiCoupler_top/adc0_ch3_lpf_400k_data[61]} {DiCoupler_top/adc0_ch3_lpf_400k_data[62]} {DiCoupler_top/adc0_ch3_lpf_400k_data[63]}]]
connect_debug_port u_ila_1/probe5 [get_nets [list {DiCoupler_top/adc0_ch4_lpf_400k_data[0]} {DiCoupler_top/adc0_ch4_lpf_400k_data[1]} {DiCoupler_top/adc0_ch4_lpf_400k_data[2]} {DiCoupler_top/adc0_ch4_lpf_400k_data[3]} {DiCoupler_top/adc0_ch4_lpf_400k_data[4]} {DiCoupler_top/adc0_ch4_lpf_400k_data[5]} {DiCoupler_top/adc0_ch4_lpf_400k_data[6]} {DiCoupler_top/adc0_ch4_lpf_400k_data[7]} {DiCoupler_top/adc0_ch4_lpf_400k_data[8]} {DiCoupler_top/adc0_ch4_lpf_400k_data[9]} {DiCoupler_top/adc0_ch4_lpf_400k_data[10]} {DiCoupler_top/adc0_ch4_lpf_400k_data[11]} {DiCoupler_top/adc0_ch4_lpf_400k_data[12]} {DiCoupler_top/adc0_ch4_lpf_400k_data[13]} {DiCoupler_top/adc0_ch4_lpf_400k_data[14]} {DiCoupler_top/adc0_ch4_lpf_400k_data[15]} {DiCoupler_top/adc0_ch4_lpf_400k_data[16]} {DiCoupler_top/adc0_ch4_lpf_400k_data[17]} {DiCoupler_top/adc0_ch4_lpf_400k_data[18]} {DiCoupler_top/adc0_ch4_lpf_400k_data[19]} {DiCoupler_top/adc0_ch4_lpf_400k_data[20]} {DiCoupler_top/adc0_ch4_lpf_400k_data[21]} {DiCoupler_top/adc0_ch4_lpf_400k_data[22]} {DiCoupler_top/adc0_ch4_lpf_400k_data[23]} {DiCoupler_top/adc0_ch4_lpf_400k_data[24]} {DiCoupler_top/adc0_ch4_lpf_400k_data[25]} {DiCoupler_top/adc0_ch4_lpf_400k_data[26]} {DiCoupler_top/adc0_ch4_lpf_400k_data[27]} {DiCoupler_top/adc0_ch4_lpf_400k_data[28]} {DiCoupler_top/adc0_ch4_lpf_400k_data[29]} {DiCoupler_top/adc0_ch4_lpf_400k_data[30]} {DiCoupler_top/adc0_ch4_lpf_400k_data[31]} {DiCoupler_top/adc0_ch4_lpf_400k_data[32]} {DiCoupler_top/adc0_ch4_lpf_400k_data[33]} {DiCoupler_top/adc0_ch4_lpf_400k_data[34]} {DiCoupler_top/adc0_ch4_lpf_400k_data[35]} {DiCoupler_top/adc0_ch4_lpf_400k_data[36]} {DiCoupler_top/adc0_ch4_lpf_400k_data[37]} {DiCoupler_top/adc0_ch4_lpf_400k_data[38]} {DiCoupler_top/adc0_ch4_lpf_400k_data[39]} {DiCoupler_top/adc0_ch4_lpf_400k_data[40]} {DiCoupler_top/adc0_ch4_lpf_400k_data[41]} {DiCoupler_top/adc0_ch4_lpf_400k_data[42]} {DiCoupler_top/adc0_ch4_lpf_400k_data[43]} {DiCoupler_top/adc0_ch4_lpf_400k_data[44]} {DiCoupler_top/adc0_ch4_lpf_400k_data[45]} {DiCoupler_top/adc0_ch4_lpf_400k_data[46]} {DiCoupler_top/adc0_ch4_lpf_400k_data[47]} {DiCoupler_top/adc0_ch4_lpf_400k_data[48]} {DiCoupler_top/adc0_ch4_lpf_400k_data[49]} {DiCoupler_top/adc0_ch4_lpf_400k_data[50]} {DiCoupler_top/adc0_ch4_lpf_400k_data[51]} {DiCoupler_top/adc0_ch4_lpf_400k_data[52]} {DiCoupler_top/adc0_ch4_lpf_400k_data[53]} {DiCoupler_top/adc0_ch4_lpf_400k_data[54]} {DiCoupler_top/adc0_ch4_lpf_400k_data[55]} {DiCoupler_top/adc0_ch4_lpf_400k_data[56]} {DiCoupler_top/adc0_ch4_lpf_400k_data[57]} {DiCoupler_top/adc0_ch4_lpf_400k_data[58]} {DiCoupler_top/adc0_ch4_lpf_400k_data[59]} {DiCoupler_top/adc0_ch4_lpf_400k_data[60]} {DiCoupler_top/adc0_ch4_lpf_400k_data[61]} {DiCoupler_top/adc0_ch4_lpf_400k_data[62]} {DiCoupler_top/adc0_ch4_lpf_400k_data[63]}]]
connect_debug_port u_ila_1/probe7 [get_nets [list {DiCoupler_top/adc0_ch4_lpf_data[0]} {DiCoupler_top/adc0_ch4_lpf_data[1]} {DiCoupler_top/adc0_ch4_lpf_data[2]} {DiCoupler_top/adc0_ch4_lpf_data[3]} {DiCoupler_top/adc0_ch4_lpf_data[4]} {DiCoupler_top/adc0_ch4_lpf_data[5]} {DiCoupler_top/adc0_ch4_lpf_data[6]} {DiCoupler_top/adc0_ch4_lpf_data[7]} {DiCoupler_top/adc0_ch4_lpf_data[8]} {DiCoupler_top/adc0_ch4_lpf_data[9]} {DiCoupler_top/adc0_ch4_lpf_data[10]} {DiCoupler_top/adc0_ch4_lpf_data[11]} {DiCoupler_top/adc0_ch4_lpf_data[12]} {DiCoupler_top/adc0_ch4_lpf_data[13]} {DiCoupler_top/adc0_ch4_lpf_data[14]} {DiCoupler_top/adc0_ch4_lpf_data[15]} {DiCoupler_top/adc0_ch4_lpf_data[16]} {DiCoupler_top/adc0_ch4_lpf_data[17]} {DiCoupler_top/adc0_ch4_lpf_data[18]} {DiCoupler_top/adc0_ch4_lpf_data[19]} {DiCoupler_top/adc0_ch4_lpf_data[20]} {DiCoupler_top/adc0_ch4_lpf_data[21]} {DiCoupler_top/adc0_ch4_lpf_data[22]} {DiCoupler_top/adc0_ch4_lpf_data[23]} {DiCoupler_top/adc0_ch4_lpf_data[24]} {DiCoupler_top/adc0_ch4_lpf_data[25]} {DiCoupler_top/adc0_ch4_lpf_data[26]} {DiCoupler_top/adc0_ch4_lpf_data[27]} {DiCoupler_top/adc0_ch4_lpf_data[28]} {DiCoupler_top/adc0_ch4_lpf_data[29]} {DiCoupler_top/adc0_ch4_lpf_data[30]} {DiCoupler_top/adc0_ch4_lpf_data[31]} {DiCoupler_top/adc0_ch4_lpf_data[32]} {DiCoupler_top/adc0_ch4_lpf_data[33]} {DiCoupler_top/adc0_ch4_lpf_data[34]} {DiCoupler_top/adc0_ch4_lpf_data[35]} {DiCoupler_top/adc0_ch4_lpf_data[36]} {DiCoupler_top/adc0_ch4_lpf_data[37]} {DiCoupler_top/adc0_ch4_lpf_data[38]} {DiCoupler_top/adc0_ch4_lpf_data[39]} {DiCoupler_top/adc0_ch4_lpf_data[40]} {DiCoupler_top/adc0_ch4_lpf_data[41]} {DiCoupler_top/adc0_ch4_lpf_data[42]} {DiCoupler_top/adc0_ch4_lpf_data[43]} {DiCoupler_top/adc0_ch4_lpf_data[44]} {DiCoupler_top/adc0_ch4_lpf_data[45]} {DiCoupler_top/adc0_ch4_lpf_data[46]} {DiCoupler_top/adc0_ch4_lpf_data[47]} {DiCoupler_top/adc0_ch4_lpf_data[48]} {DiCoupler_top/adc0_ch4_lpf_data[49]} {DiCoupler_top/adc0_ch4_lpf_data[50]} {DiCoupler_top/adc0_ch4_lpf_data[51]} {DiCoupler_top/adc0_ch4_lpf_data[52]} {DiCoupler_top/adc0_ch4_lpf_data[53]} {DiCoupler_top/adc0_ch4_lpf_data[54]} {DiCoupler_top/adc0_ch4_lpf_data[55]} {DiCoupler_top/adc0_ch4_lpf_data[56]} {DiCoupler_top/adc0_ch4_lpf_data[57]} {DiCoupler_top/adc0_ch4_lpf_data[58]} {DiCoupler_top/adc0_ch4_lpf_data[59]} {DiCoupler_top/adc0_ch4_lpf_data[60]} {DiCoupler_top/adc0_ch4_lpf_data[61]} {DiCoupler_top/adc0_ch4_lpf_data[62]} {DiCoupler_top/adc0_ch4_lpf_data[63]}]]
connect_debug_port u_ila_1/probe9 [get_nets [list {DiCoupler_top/adc1_ch4_lpf_400k_data[0]} {DiCoupler_top/adc1_ch4_lpf_400k_data[1]} {DiCoupler_top/adc1_ch4_lpf_400k_data[2]} {DiCoupler_top/adc1_ch4_lpf_400k_data[3]} {DiCoupler_top/adc1_ch4_lpf_400k_data[4]} {DiCoupler_top/adc1_ch4_lpf_400k_data[5]} {DiCoupler_top/adc1_ch4_lpf_400k_data[6]} {DiCoupler_top/adc1_ch4_lpf_400k_data[7]} {DiCoupler_top/adc1_ch4_lpf_400k_data[8]} {DiCoupler_top/adc1_ch4_lpf_400k_data[9]} {DiCoupler_top/adc1_ch4_lpf_400k_data[10]} {DiCoupler_top/adc1_ch4_lpf_400k_data[11]} {DiCoupler_top/adc1_ch4_lpf_400k_data[12]} {DiCoupler_top/adc1_ch4_lpf_400k_data[13]} {DiCoupler_top/adc1_ch4_lpf_400k_data[14]} {DiCoupler_top/adc1_ch4_lpf_400k_data[15]} {DiCoupler_top/adc1_ch4_lpf_400k_data[16]} {DiCoupler_top/adc1_ch4_lpf_400k_data[17]} {DiCoupler_top/adc1_ch4_lpf_400k_data[18]} {DiCoupler_top/adc1_ch4_lpf_400k_data[19]} {DiCoupler_top/adc1_ch4_lpf_400k_data[20]} {DiCoupler_top/adc1_ch4_lpf_400k_data[21]} {DiCoupler_top/adc1_ch4_lpf_400k_data[22]} {DiCoupler_top/adc1_ch4_lpf_400k_data[23]} {DiCoupler_top/adc1_ch4_lpf_400k_data[24]} {DiCoupler_top/adc1_ch4_lpf_400k_data[25]} {DiCoupler_top/adc1_ch4_lpf_400k_data[26]} {DiCoupler_top/adc1_ch4_lpf_400k_data[27]} {DiCoupler_top/adc1_ch4_lpf_400k_data[28]} {DiCoupler_top/adc1_ch4_lpf_400k_data[29]} {DiCoupler_top/adc1_ch4_lpf_400k_data[30]} {DiCoupler_top/adc1_ch4_lpf_400k_data[31]} {DiCoupler_top/adc1_ch4_lpf_400k_data[32]} {DiCoupler_top/adc1_ch4_lpf_400k_data[33]} {DiCoupler_top/adc1_ch4_lpf_400k_data[34]} {DiCoupler_top/adc1_ch4_lpf_400k_data[35]} {DiCoupler_top/adc1_ch4_lpf_400k_data[36]} {DiCoupler_top/adc1_ch4_lpf_400k_data[37]} {DiCoupler_top/adc1_ch4_lpf_400k_data[38]} {DiCoupler_top/adc1_ch4_lpf_400k_data[39]} {DiCoupler_top/adc1_ch4_lpf_400k_data[40]} {DiCoupler_top/adc1_ch4_lpf_400k_data[41]} {DiCoupler_top/adc1_ch4_lpf_400k_data[42]} {DiCoupler_top/adc1_ch4_lpf_400k_data[43]} {DiCoupler_top/adc1_ch4_lpf_400k_data[44]} {DiCoupler_top/adc1_ch4_lpf_400k_data[45]} {DiCoupler_top/adc1_ch4_lpf_400k_data[46]} {DiCoupler_top/adc1_ch4_lpf_400k_data[47]} {DiCoupler_top/adc1_ch4_lpf_400k_data[48]} {DiCoupler_top/adc1_ch4_lpf_400k_data[49]} {DiCoupler_top/adc1_ch4_lpf_400k_data[50]} {DiCoupler_top/adc1_ch4_lpf_400k_data[51]} {DiCoupler_top/adc1_ch4_lpf_400k_data[52]} {DiCoupler_top/adc1_ch4_lpf_400k_data[53]} {DiCoupler_top/adc1_ch4_lpf_400k_data[54]} {DiCoupler_top/adc1_ch4_lpf_400k_data[55]} {DiCoupler_top/adc1_ch4_lpf_400k_data[56]} {DiCoupler_top/adc1_ch4_lpf_400k_data[57]} {DiCoupler_top/adc1_ch4_lpf_400k_data[58]} {DiCoupler_top/adc1_ch4_lpf_400k_data[59]} {DiCoupler_top/adc1_ch4_lpf_400k_data[60]} {DiCoupler_top/adc1_ch4_lpf_400k_data[61]} {DiCoupler_top/adc1_ch4_lpf_400k_data[62]} {DiCoupler_top/adc1_ch4_lpf_400k_data[63]}]]
connect_debug_port u_ila_1/probe10 [get_nets [list {DiCoupler_top/adc1_ch4_lpf_data[0]} {DiCoupler_top/adc1_ch4_lpf_data[1]} {DiCoupler_top/adc1_ch4_lpf_data[2]} {DiCoupler_top/adc1_ch4_lpf_data[3]} {DiCoupler_top/adc1_ch4_lpf_data[4]} {DiCoupler_top/adc1_ch4_lpf_data[5]} {DiCoupler_top/adc1_ch4_lpf_data[6]} {DiCoupler_top/adc1_ch4_lpf_data[7]} {DiCoupler_top/adc1_ch4_lpf_data[8]} {DiCoupler_top/adc1_ch4_lpf_data[9]} {DiCoupler_top/adc1_ch4_lpf_data[10]} {DiCoupler_top/adc1_ch4_lpf_data[11]} {DiCoupler_top/adc1_ch4_lpf_data[12]} {DiCoupler_top/adc1_ch4_lpf_data[13]} {DiCoupler_top/adc1_ch4_lpf_data[14]} {DiCoupler_top/adc1_ch4_lpf_data[15]} {DiCoupler_top/adc1_ch4_lpf_data[16]} {DiCoupler_top/adc1_ch4_lpf_data[17]} {DiCoupler_top/adc1_ch4_lpf_data[18]} {DiCoupler_top/adc1_ch4_lpf_data[19]} {DiCoupler_top/adc1_ch4_lpf_data[20]} {DiCoupler_top/adc1_ch4_lpf_data[21]} {DiCoupler_top/adc1_ch4_lpf_data[22]} {DiCoupler_top/adc1_ch4_lpf_data[23]} {DiCoupler_top/adc1_ch4_lpf_data[24]} {DiCoupler_top/adc1_ch4_lpf_data[25]} {DiCoupler_top/adc1_ch4_lpf_data[26]} {DiCoupler_top/adc1_ch4_lpf_data[27]} {DiCoupler_top/adc1_ch4_lpf_data[28]} {DiCoupler_top/adc1_ch4_lpf_data[29]} {DiCoupler_top/adc1_ch4_lpf_data[30]} {DiCoupler_top/adc1_ch4_lpf_data[31]} {DiCoupler_top/adc1_ch4_lpf_data[32]} {DiCoupler_top/adc1_ch4_lpf_data[33]} {DiCoupler_top/adc1_ch4_lpf_data[34]} {DiCoupler_top/adc1_ch4_lpf_data[35]} {DiCoupler_top/adc1_ch4_lpf_data[36]} {DiCoupler_top/adc1_ch4_lpf_data[37]} {DiCoupler_top/adc1_ch4_lpf_data[38]} {DiCoupler_top/adc1_ch4_lpf_data[39]} {DiCoupler_top/adc1_ch4_lpf_data[40]} {DiCoupler_top/adc1_ch4_lpf_data[41]} {DiCoupler_top/adc1_ch4_lpf_data[42]} {DiCoupler_top/adc1_ch4_lpf_data[43]} {DiCoupler_top/adc1_ch4_lpf_data[44]} {DiCoupler_top/adc1_ch4_lpf_data[45]} {DiCoupler_top/adc1_ch4_lpf_data[46]} {DiCoupler_top/adc1_ch4_lpf_data[47]} {DiCoupler_top/adc1_ch4_lpf_data[48]} {DiCoupler_top/adc1_ch4_lpf_data[49]} {DiCoupler_top/adc1_ch4_lpf_data[50]} {DiCoupler_top/adc1_ch4_lpf_data[51]} {DiCoupler_top/adc1_ch4_lpf_data[52]} {DiCoupler_top/adc1_ch4_lpf_data[53]} {DiCoupler_top/adc1_ch4_lpf_data[54]} {DiCoupler_top/adc1_ch4_lpf_data[55]} {DiCoupler_top/adc1_ch4_lpf_data[56]} {DiCoupler_top/adc1_ch4_lpf_data[57]} {DiCoupler_top/adc1_ch4_lpf_data[58]} {DiCoupler_top/adc1_ch4_lpf_data[59]} {DiCoupler_top/adc1_ch4_lpf_data[60]} {DiCoupler_top/adc1_ch4_lpf_data[61]} {DiCoupler_top/adc1_ch4_lpf_data[62]} {DiCoupler_top/adc1_ch4_lpf_data[63]}]]
connect_debug_port u_ila_1/probe13 [get_nets [list {DiCoupler_top/adc0_ch3_lpf_data[0]} {DiCoupler_top/adc0_ch3_lpf_data[1]} {DiCoupler_top/adc0_ch3_lpf_data[2]} {DiCoupler_top/adc0_ch3_lpf_data[3]} {DiCoupler_top/adc0_ch3_lpf_data[4]} {DiCoupler_top/adc0_ch3_lpf_data[5]} {DiCoupler_top/adc0_ch3_lpf_data[6]} {DiCoupler_top/adc0_ch3_lpf_data[7]} {DiCoupler_top/adc0_ch3_lpf_data[8]} {DiCoupler_top/adc0_ch3_lpf_data[9]} {DiCoupler_top/adc0_ch3_lpf_data[10]} {DiCoupler_top/adc0_ch3_lpf_data[11]} {DiCoupler_top/adc0_ch3_lpf_data[12]} {DiCoupler_top/adc0_ch3_lpf_data[13]} {DiCoupler_top/adc0_ch3_lpf_data[14]} {DiCoupler_top/adc0_ch3_lpf_data[15]} {DiCoupler_top/adc0_ch3_lpf_data[16]} {DiCoupler_top/adc0_ch3_lpf_data[17]} {DiCoupler_top/adc0_ch3_lpf_data[18]} {DiCoupler_top/adc0_ch3_lpf_data[19]} {DiCoupler_top/adc0_ch3_lpf_data[20]} {DiCoupler_top/adc0_ch3_lpf_data[21]} {DiCoupler_top/adc0_ch3_lpf_data[22]} {DiCoupler_top/adc0_ch3_lpf_data[23]} {DiCoupler_top/adc0_ch3_lpf_data[24]} {DiCoupler_top/adc0_ch3_lpf_data[25]} {DiCoupler_top/adc0_ch3_lpf_data[26]} {DiCoupler_top/adc0_ch3_lpf_data[27]} {DiCoupler_top/adc0_ch3_lpf_data[28]} {DiCoupler_top/adc0_ch3_lpf_data[29]} {DiCoupler_top/adc0_ch3_lpf_data[30]} {DiCoupler_top/adc0_ch3_lpf_data[31]} {DiCoupler_top/adc0_ch3_lpf_data[32]} {DiCoupler_top/adc0_ch3_lpf_data[33]} {DiCoupler_top/adc0_ch3_lpf_data[34]} {DiCoupler_top/adc0_ch3_lpf_data[35]} {DiCoupler_top/adc0_ch3_lpf_data[36]} {DiCoupler_top/adc0_ch3_lpf_data[37]} {DiCoupler_top/adc0_ch3_lpf_data[38]} {DiCoupler_top/adc0_ch3_lpf_data[39]} {DiCoupler_top/adc0_ch3_lpf_data[40]} {DiCoupler_top/adc0_ch3_lpf_data[41]} {DiCoupler_top/adc0_ch3_lpf_data[42]} {DiCoupler_top/adc0_ch3_lpf_data[43]} {DiCoupler_top/adc0_ch3_lpf_data[44]} {DiCoupler_top/adc0_ch3_lpf_data[45]} {DiCoupler_top/adc0_ch3_lpf_data[46]} {DiCoupler_top/adc0_ch3_lpf_data[47]} {DiCoupler_top/adc0_ch3_lpf_data[48]} {DiCoupler_top/adc0_ch3_lpf_data[49]} {DiCoupler_top/adc0_ch3_lpf_data[50]} {DiCoupler_top/adc0_ch3_lpf_data[51]} {DiCoupler_top/adc0_ch3_lpf_data[52]} {DiCoupler_top/adc0_ch3_lpf_data[53]} {DiCoupler_top/adc0_ch3_lpf_data[54]} {DiCoupler_top/adc0_ch3_lpf_data[55]} {DiCoupler_top/adc0_ch3_lpf_data[56]} {DiCoupler_top/adc0_ch3_lpf_data[57]} {DiCoupler_top/adc0_ch3_lpf_data[58]} {DiCoupler_top/adc0_ch3_lpf_data[59]} {DiCoupler_top/adc0_ch3_lpf_data[60]} {DiCoupler_top/adc0_ch3_lpf_data[61]} {DiCoupler_top/adc0_ch3_lpf_data[62]} {DiCoupler_top/adc0_ch3_lpf_data[63]}]]
connect_debug_port u_ila_1/probe24 [get_nets [list DiCoupler_top/adc0_ch3_lpf_400k_vld]]
connect_debug_port u_ila_1/probe25 [get_nets [list DiCoupler_top/adc0_ch3_lpf_vld]]
connect_debug_port u_ila_1/probe26 [get_nets [list DiCoupler_top/adc0_ch4_lpf_400k_vld]]
connect_debug_port u_ila_1/probe27 [get_nets [list DiCoupler_top/adc0_ch4_lpf_vld]]
connect_debug_port u_ila_1/probe32 [get_nets [list DiCoupler_top/adc1_ch3_lpf_400k_vld]]
connect_debug_port u_ila_1/probe33 [get_nets [list DiCoupler_top/adc1_ch3_lpf_vld]]
connect_debug_port u_ila_1/probe34 [get_nets [list DiCoupler_top/adc1_ch4_lpf_400k_vld]]
connect_debug_port u_ila_1/probe35 [get_nets [list DiCoupler_top/adc1_ch4_lpf_vld]]
connect_debug_port u_ila_2/probe28 [get_nets [list {DiCoupler_top/JX3_400k_result[0]} {DiCoupler_top/JX3_400k_result[1]} {DiCoupler_top/JX3_400k_result[2]} {DiCoupler_top/JX3_400k_result[3]} {DiCoupler_top/JX3_400k_result[4]} {DiCoupler_top/JX3_400k_result[5]} {DiCoupler_top/JX3_400k_result[6]} {DiCoupler_top/JX3_400k_result[7]} {DiCoupler_top/JX3_400k_result[8]} {DiCoupler_top/JX3_400k_result[9]} {DiCoupler_top/JX3_400k_result[10]} {DiCoupler_top/JX3_400k_result[11]} {DiCoupler_top/JX3_400k_result[12]} {DiCoupler_top/JX3_400k_result[13]} {DiCoupler_top/JX3_400k_result[14]} {DiCoupler_top/JX3_400k_result[15]} {DiCoupler_top/JX3_400k_result[16]} {DiCoupler_top/JX3_400k_result[17]} {DiCoupler_top/JX3_400k_result[18]} {DiCoupler_top/JX3_400k_result[19]} {DiCoupler_top/JX3_400k_result[20]} {DiCoupler_top/JX3_400k_result[21]} {DiCoupler_top/JX3_400k_result[22]} {DiCoupler_top/JX3_400k_result[23]} {DiCoupler_top/JX3_400k_result[24]} {DiCoupler_top/JX3_400k_result[25]} {DiCoupler_top/JX3_400k_result[26]} {DiCoupler_top/JX3_400k_result[27]} {DiCoupler_top/JX3_400k_result[28]} {DiCoupler_top/JX3_400k_result[29]} {DiCoupler_top/JX3_400k_result[30]} {DiCoupler_top/JX3_400k_result[31]}]]
connect_debug_port u_ila_2/probe30 [get_nets [list {DiCoupler_top/JX3_result[0]} {DiCoupler_top/JX3_result[1]} {DiCoupler_top/JX3_result[2]} {DiCoupler_top/JX3_result[3]} {DiCoupler_top/JX3_result[4]} {DiCoupler_top/JX3_result[5]} {DiCoupler_top/JX3_result[6]} {DiCoupler_top/JX3_result[7]} {DiCoupler_top/JX3_result[8]} {DiCoupler_top/JX3_result[9]} {DiCoupler_top/JX3_result[10]} {DiCoupler_top/JX3_result[11]} {DiCoupler_top/JX3_result[12]} {DiCoupler_top/JX3_result[13]} {DiCoupler_top/JX3_result[14]} {DiCoupler_top/JX3_result[15]} {DiCoupler_top/JX3_result[16]} {DiCoupler_top/JX3_result[17]} {DiCoupler_top/JX3_result[18]} {DiCoupler_top/JX3_result[19]} {DiCoupler_top/JX3_result[20]} {DiCoupler_top/JX3_result[21]} {DiCoupler_top/JX3_result[22]} {DiCoupler_top/JX3_result[23]} {DiCoupler_top/JX3_result[24]} {DiCoupler_top/JX3_result[25]} {DiCoupler_top/JX3_result[26]} {DiCoupler_top/JX3_result[27]} {DiCoupler_top/JX3_result[28]} {DiCoupler_top/JX3_result[29]} {DiCoupler_top/JX3_result[30]} {DiCoupler_top/JX3_result[31]}]]
connect_debug_port u_ila_2/probe31 [get_nets [list {DiCoupler_top/JX4_400k_result[0]} {DiCoupler_top/JX4_400k_result[1]} {DiCoupler_top/JX4_400k_result[2]} {DiCoupler_top/JX4_400k_result[3]} {DiCoupler_top/JX4_400k_result[4]} {DiCoupler_top/JX4_400k_result[5]} {DiCoupler_top/JX4_400k_result[6]} {DiCoupler_top/JX4_400k_result[7]} {DiCoupler_top/JX4_400k_result[8]} {DiCoupler_top/JX4_400k_result[9]} {DiCoupler_top/JX4_400k_result[10]} {DiCoupler_top/JX4_400k_result[11]} {DiCoupler_top/JX4_400k_result[12]} {DiCoupler_top/JX4_400k_result[13]} {DiCoupler_top/JX4_400k_result[14]} {DiCoupler_top/JX4_400k_result[15]} {DiCoupler_top/JX4_400k_result[16]} {DiCoupler_top/JX4_400k_result[17]} {DiCoupler_top/JX4_400k_result[18]} {DiCoupler_top/JX4_400k_result[19]} {DiCoupler_top/JX4_400k_result[20]} {DiCoupler_top/JX4_400k_result[21]} {DiCoupler_top/JX4_400k_result[22]} {DiCoupler_top/JX4_400k_result[23]} {DiCoupler_top/JX4_400k_result[24]} {DiCoupler_top/JX4_400k_result[25]} {DiCoupler_top/JX4_400k_result[26]} {DiCoupler_top/JX4_400k_result[27]} {DiCoupler_top/JX4_400k_result[28]} {DiCoupler_top/JX4_400k_result[29]} {DiCoupler_top/JX4_400k_result[30]} {DiCoupler_top/JX4_400k_result[31]}]]
connect_debug_port u_ila_2/probe32 [get_nets [list {DiCoupler_top/JX4_result[0]} {DiCoupler_top/JX4_result[1]} {DiCoupler_top/JX4_result[2]} {DiCoupler_top/JX4_result[3]} {DiCoupler_top/JX4_result[4]} {DiCoupler_top/JX4_result[5]} {DiCoupler_top/JX4_result[6]} {DiCoupler_top/JX4_result[7]} {DiCoupler_top/JX4_result[8]} {DiCoupler_top/JX4_result[9]} {DiCoupler_top/JX4_result[10]} {DiCoupler_top/JX4_result[11]} {DiCoupler_top/JX4_result[12]} {DiCoupler_top/JX4_result[13]} {DiCoupler_top/JX4_result[14]} {DiCoupler_top/JX4_result[15]} {DiCoupler_top/JX4_result[16]} {DiCoupler_top/JX4_result[17]} {DiCoupler_top/JX4_result[18]} {DiCoupler_top/JX4_result[19]} {DiCoupler_top/JX4_result[20]} {DiCoupler_top/JX4_result[21]} {DiCoupler_top/JX4_result[22]} {DiCoupler_top/JX4_result[23]} {DiCoupler_top/JX4_result[24]} {DiCoupler_top/JX4_result[25]} {DiCoupler_top/JX4_result[26]} {DiCoupler_top/JX4_result[27]} {DiCoupler_top/JX4_result[28]} {DiCoupler_top/JX4_result[29]} {DiCoupler_top/JX4_result[30]} {DiCoupler_top/JX4_result[31]}]]
connect_debug_port u_ila_2/probe51 [get_nets [list {DiCoupler_top/R3_400k_result[0]} {DiCoupler_top/R3_400k_result[1]} {DiCoupler_top/R3_400k_result[2]} {DiCoupler_top/R3_400k_result[3]} {DiCoupler_top/R3_400k_result[4]} {DiCoupler_top/R3_400k_result[5]} {DiCoupler_top/R3_400k_result[6]} {DiCoupler_top/R3_400k_result[7]} {DiCoupler_top/R3_400k_result[8]} {DiCoupler_top/R3_400k_result[9]} {DiCoupler_top/R3_400k_result[10]} {DiCoupler_top/R3_400k_result[11]} {DiCoupler_top/R3_400k_result[12]} {DiCoupler_top/R3_400k_result[13]} {DiCoupler_top/R3_400k_result[14]} {DiCoupler_top/R3_400k_result[15]} {DiCoupler_top/R3_400k_result[16]} {DiCoupler_top/R3_400k_result[17]} {DiCoupler_top/R3_400k_result[18]} {DiCoupler_top/R3_400k_result[19]} {DiCoupler_top/R3_400k_result[20]} {DiCoupler_top/R3_400k_result[21]} {DiCoupler_top/R3_400k_result[22]} {DiCoupler_top/R3_400k_result[23]} {DiCoupler_top/R3_400k_result[24]} {DiCoupler_top/R3_400k_result[25]} {DiCoupler_top/R3_400k_result[26]} {DiCoupler_top/R3_400k_result[27]} {DiCoupler_top/R3_400k_result[28]} {DiCoupler_top/R3_400k_result[29]} {DiCoupler_top/R3_400k_result[30]} {DiCoupler_top/R3_400k_result[31]}]]
connect_debug_port u_ila_2/probe52 [get_nets [list {DiCoupler_top/R3_result[0]} {DiCoupler_top/R3_result[1]} {DiCoupler_top/R3_result[2]} {DiCoupler_top/R3_result[3]} {DiCoupler_top/R3_result[4]} {DiCoupler_top/R3_result[5]} {DiCoupler_top/R3_result[6]} {DiCoupler_top/R3_result[7]} {DiCoupler_top/R3_result[8]} {DiCoupler_top/R3_result[9]} {DiCoupler_top/R3_result[10]} {DiCoupler_top/R3_result[11]} {DiCoupler_top/R3_result[12]} {DiCoupler_top/R3_result[13]} {DiCoupler_top/R3_result[14]} {DiCoupler_top/R3_result[15]} {DiCoupler_top/R3_result[16]} {DiCoupler_top/R3_result[17]} {DiCoupler_top/R3_result[18]} {DiCoupler_top/R3_result[19]} {DiCoupler_top/R3_result[20]} {DiCoupler_top/R3_result[21]} {DiCoupler_top/R3_result[22]} {DiCoupler_top/R3_result[23]} {DiCoupler_top/R3_result[24]} {DiCoupler_top/R3_result[25]} {DiCoupler_top/R3_result[26]} {DiCoupler_top/R3_result[27]} {DiCoupler_top/R3_result[28]} {DiCoupler_top/R3_result[29]} {DiCoupler_top/R3_result[30]} {DiCoupler_top/R3_result[31]}]]
connect_debug_port u_ila_2/probe53 [get_nets [list {DiCoupler_top/R4_400k_result[0]} {DiCoupler_top/R4_400k_result[1]} {DiCoupler_top/R4_400k_result[2]} {DiCoupler_top/R4_400k_result[3]} {DiCoupler_top/R4_400k_result[4]} {DiCoupler_top/R4_400k_result[5]} {DiCoupler_top/R4_400k_result[6]} {DiCoupler_top/R4_400k_result[7]} {DiCoupler_top/R4_400k_result[8]} {DiCoupler_top/R4_400k_result[9]} {DiCoupler_top/R4_400k_result[10]} {DiCoupler_top/R4_400k_result[11]} {DiCoupler_top/R4_400k_result[12]} {DiCoupler_top/R4_400k_result[13]} {DiCoupler_top/R4_400k_result[14]} {DiCoupler_top/R4_400k_result[15]} {DiCoupler_top/R4_400k_result[16]} {DiCoupler_top/R4_400k_result[17]} {DiCoupler_top/R4_400k_result[18]} {DiCoupler_top/R4_400k_result[19]} {DiCoupler_top/R4_400k_result[20]} {DiCoupler_top/R4_400k_result[21]} {DiCoupler_top/R4_400k_result[22]} {DiCoupler_top/R4_400k_result[23]} {DiCoupler_top/R4_400k_result[24]} {DiCoupler_top/R4_400k_result[25]} {DiCoupler_top/R4_400k_result[26]} {DiCoupler_top/R4_400k_result[27]} {DiCoupler_top/R4_400k_result[28]} {DiCoupler_top/R4_400k_result[29]} {DiCoupler_top/R4_400k_result[30]} {DiCoupler_top/R4_400k_result[31]}]]
connect_debug_port u_ila_2/probe54 [get_nets [list {DiCoupler_top/R4_result[0]} {DiCoupler_top/R4_result[1]} {DiCoupler_top/R4_result[2]} {DiCoupler_top/R4_result[3]} {DiCoupler_top/R4_result[4]} {DiCoupler_top/R4_result[5]} {DiCoupler_top/R4_result[6]} {DiCoupler_top/R4_result[7]} {DiCoupler_top/R4_result[8]} {DiCoupler_top/R4_result[9]} {DiCoupler_top/R4_result[10]} {DiCoupler_top/R4_result[11]} {DiCoupler_top/R4_result[12]} {DiCoupler_top/R4_result[13]} {DiCoupler_top/R4_result[14]} {DiCoupler_top/R4_result[15]} {DiCoupler_top/R4_result[16]} {DiCoupler_top/R4_result[17]} {DiCoupler_top/R4_result[18]} {DiCoupler_top/R4_result[19]} {DiCoupler_top/R4_result[20]} {DiCoupler_top/R4_result[21]} {DiCoupler_top/R4_result[22]} {DiCoupler_top/R4_result[23]} {DiCoupler_top/R4_result[24]} {DiCoupler_top/R4_result[25]} {DiCoupler_top/R4_result[26]} {DiCoupler_top/R4_result[27]} {DiCoupler_top/R4_result[28]} {DiCoupler_top/R4_result[29]} {DiCoupler_top/R4_result[30]} {DiCoupler_top/R4_result[31]}]]

connect_debug_port u_ila_0/probe1 [get_nets [list {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[0]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[1]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[2]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[3]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[4]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[5]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[6]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[7]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[8]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[9]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[10]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[11]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[12]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[13]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[14]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[15]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[16]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[17]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[18]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[19]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[20]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[21]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[22]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[23]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[24]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[25]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[26]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[27]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[28]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[29]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[30]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/lock_cnt[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[0]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[1]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[2]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[3]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[4]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[5]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[6]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[7]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[8]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[9]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[10]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[11]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[12]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[13]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[14]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[15]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[16]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[17]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[18]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[19]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[20]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[21]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[22]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[23]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[24]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[25]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[26]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[27]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[28]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[29]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[30]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_total[31]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[0]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[1]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[2]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[3]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[4]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[5]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[6]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[7]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[8]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[9]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[10]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[11]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[12]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[13]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[14]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[15]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[16]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[17]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[18]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[19]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[20]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[21]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[22]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[23]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[24]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[25]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[26]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[27]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[28]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[29]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[30]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_cnt[31]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[0]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[1]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[2]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[3]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[4]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[5]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[6]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[7]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[8]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[9]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[10]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[11]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[12]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[13]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[14]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[15]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[16]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[17]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[18]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[19]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[20]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[21]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[22]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[23]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[24]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[25]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[26]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[27]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[28]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[29]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[30]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/period_cnt[31]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[0]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[1]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[2]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[3]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[4]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[5]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[6]} {DiCoupler_top/FREQ_RTK_MEASURE_HF/HALF_FREQ_NUM[7]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list DiCoupler_top/FREQ_RTK_MEASURE_HF/neg_pwm]]
connect_debug_port u_ila_0/probe30 [get_nets [list DiCoupler_top/FREQ_RTK_MEASURE_HF/pos_pwm]]

connect_debug_port u_ila_0/probe0 [get_nets [list {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[0]} {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[1]} {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[2]} {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[3]} {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[4]} {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[5]} {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[6]} {DiCoupler_top/FREQ_RTK_MEASURE_LF/HALF_FREQ_NUM[7]}]]



connect_debug_port u_ila_0/probe23 [get_nets [list {DiCoupler_top/CALIB_R2[0]} {DiCoupler_top/CALIB_R2[1]} {DiCoupler_top/CALIB_R2[2]} {DiCoupler_top/CALIB_R2[3]} {DiCoupler_top/CALIB_R2[4]} {DiCoupler_top/CALIB_R2[5]} {DiCoupler_top/CALIB_R2[6]} {DiCoupler_top/CALIB_R2[7]} {DiCoupler_top/CALIB_R2[8]} {DiCoupler_top/CALIB_R2[9]} {DiCoupler_top/CALIB_R2[10]} {DiCoupler_top/CALIB_R2[11]} {DiCoupler_top/CALIB_R2[12]} {DiCoupler_top/CALIB_R2[13]} {DiCoupler_top/CALIB_R2[14]} {DiCoupler_top/CALIB_R2[15]} {DiCoupler_top/CALIB_R2[16]} {DiCoupler_top/CALIB_R2[17]} {DiCoupler_top/CALIB_R2[18]} {DiCoupler_top/CALIB_R2[19]} {DiCoupler_top/CALIB_R2[20]} {DiCoupler_top/CALIB_R2[21]} {DiCoupler_top/CALIB_R2[22]} {DiCoupler_top/CALIB_R2[23]} {DiCoupler_top/CALIB_R2[24]} {DiCoupler_top/CALIB_R2[25]} {DiCoupler_top/CALIB_R2[26]} {DiCoupler_top/CALIB_R2[27]} {DiCoupler_top/CALIB_R2[28]} {DiCoupler_top/CALIB_R2[29]} {DiCoupler_top/CALIB_R2[30]} {DiCoupler_top/CALIB_R2[31]}]]
connect_debug_port u_ila_0/probe34 [get_nets [list {DiCoupler_top/HF_threshold2on[0]} {DiCoupler_top/HF_threshold2on[1]} {DiCoupler_top/HF_threshold2on[2]} {DiCoupler_top/HF_threshold2on[3]} {DiCoupler_top/HF_threshold2on[4]} {DiCoupler_top/HF_threshold2on[5]} {DiCoupler_top/HF_threshold2on[6]} {DiCoupler_top/HF_threshold2on[7]} {DiCoupler_top/HF_threshold2on[8]} {DiCoupler_top/HF_threshold2on[9]} {DiCoupler_top/HF_threshold2on[10]} {DiCoupler_top/HF_threshold2on[11]} {DiCoupler_top/HF_threshold2on[12]} {DiCoupler_top/HF_threshold2on[13]} {DiCoupler_top/HF_threshold2on[14]} {DiCoupler_top/HF_threshold2on[15]}]]
connect_debug_port u_ila_0/probe42 [get_nets [list {DiCoupler_top/LF_threshold2on[0]} {DiCoupler_top/LF_threshold2on[1]} {DiCoupler_top/LF_threshold2on[2]} {DiCoupler_top/LF_threshold2on[3]} {DiCoupler_top/LF_threshold2on[4]} {DiCoupler_top/LF_threshold2on[5]} {DiCoupler_top/LF_threshold2on[6]} {DiCoupler_top/LF_threshold2on[7]} {DiCoupler_top/LF_threshold2on[8]} {DiCoupler_top/LF_threshold2on[9]} {DiCoupler_top/LF_threshold2on[10]} {DiCoupler_top/LF_threshold2on[11]} {DiCoupler_top/LF_threshold2on[12]} {DiCoupler_top/LF_threshold2on[13]} {DiCoupler_top/LF_threshold2on[14]} {DiCoupler_top/LF_threshold2on[15]}]]
connect_debug_port u_ila_0/probe76 [get_nets [list {DiCoupler_top/sensor0_pulse_on_cnt[0]} {DiCoupler_top/sensor0_pulse_on_cnt[1]} {DiCoupler_top/sensor0_pulse_on_cnt[2]} {DiCoupler_top/sensor0_pulse_on_cnt[3]} {DiCoupler_top/sensor0_pulse_on_cnt[4]} {DiCoupler_top/sensor0_pulse_on_cnt[5]} {DiCoupler_top/sensor0_pulse_on_cnt[6]} {DiCoupler_top/sensor0_pulse_on_cnt[7]} {DiCoupler_top/sensor0_pulse_on_cnt[8]} {DiCoupler_top/sensor0_pulse_on_cnt[9]} {DiCoupler_top/sensor0_pulse_on_cnt[10]} {DiCoupler_top/sensor0_pulse_on_cnt[11]} {DiCoupler_top/sensor0_pulse_on_cnt[12]} {DiCoupler_top/sensor0_pulse_on_cnt[13]} {DiCoupler_top/sensor0_pulse_on_cnt[14]} {DiCoupler_top/sensor0_pulse_on_cnt[15]} {DiCoupler_top/sensor0_pulse_on_cnt[16]} {DiCoupler_top/sensor0_pulse_on_cnt[17]} {DiCoupler_top/sensor0_pulse_on_cnt[18]} {DiCoupler_top/sensor0_pulse_on_cnt[19]} {DiCoupler_top/sensor0_pulse_on_cnt[20]} {DiCoupler_top/sensor0_pulse_on_cnt[21]} {DiCoupler_top/sensor0_pulse_on_cnt[22]} {DiCoupler_top/sensor0_pulse_on_cnt[23]} {DiCoupler_top/sensor0_pulse_on_cnt[24]} {DiCoupler_top/sensor0_pulse_on_cnt[25]} {DiCoupler_top/sensor0_pulse_on_cnt[26]} {DiCoupler_top/sensor0_pulse_on_cnt[27]} {DiCoupler_top/sensor0_pulse_on_cnt[28]} {DiCoupler_top/sensor0_pulse_on_cnt[29]} {DiCoupler_top/sensor0_pulse_on_cnt[30]} {DiCoupler_top/sensor0_pulse_on_cnt[31]} {DiCoupler_top/sensor0_pulse_on_cnt[32]} {DiCoupler_top/sensor0_pulse_on_cnt[33]} {DiCoupler_top/sensor0_pulse_on_cnt[34]} {DiCoupler_top/sensor0_pulse_on_cnt[35]}]]
connect_debug_port u_ila_0/probe77 [get_nets [list {DiCoupler_top/w_pulse_gap0[0]} {DiCoupler_top/w_pulse_gap0[1]} {DiCoupler_top/w_pulse_gap0[2]} {DiCoupler_top/w_pulse_gap0[3]} {DiCoupler_top/w_pulse_gap0[4]} {DiCoupler_top/w_pulse_gap0[5]} {DiCoupler_top/w_pulse_gap0[6]} {DiCoupler_top/w_pulse_gap0[7]} {DiCoupler_top/w_pulse_gap0[8]} {DiCoupler_top/w_pulse_gap0[9]} {DiCoupler_top/w_pulse_gap0[10]} {DiCoupler_top/w_pulse_gap0[11]} {DiCoupler_top/w_pulse_gap0[12]} {DiCoupler_top/w_pulse_gap0[13]} {DiCoupler_top/w_pulse_gap0[14]} {DiCoupler_top/w_pulse_gap0[15]}]]
connect_debug_port u_ila_0/probe78 [get_nets [list {DiCoupler_top/sensor2_pulse_on_cnt[0]} {DiCoupler_top/sensor2_pulse_on_cnt[1]} {DiCoupler_top/sensor2_pulse_on_cnt[2]} {DiCoupler_top/sensor2_pulse_on_cnt[3]} {DiCoupler_top/sensor2_pulse_on_cnt[4]} {DiCoupler_top/sensor2_pulse_on_cnt[5]} {DiCoupler_top/sensor2_pulse_on_cnt[6]} {DiCoupler_top/sensor2_pulse_on_cnt[7]} {DiCoupler_top/sensor2_pulse_on_cnt[8]} {DiCoupler_top/sensor2_pulse_on_cnt[9]} {DiCoupler_top/sensor2_pulse_on_cnt[10]} {DiCoupler_top/sensor2_pulse_on_cnt[11]} {DiCoupler_top/sensor2_pulse_on_cnt[12]} {DiCoupler_top/sensor2_pulse_on_cnt[13]} {DiCoupler_top/sensor2_pulse_on_cnt[14]} {DiCoupler_top/sensor2_pulse_on_cnt[15]} {DiCoupler_top/sensor2_pulse_on_cnt[16]} {DiCoupler_top/sensor2_pulse_on_cnt[17]} {DiCoupler_top/sensor2_pulse_on_cnt[18]} {DiCoupler_top/sensor2_pulse_on_cnt[19]} {DiCoupler_top/sensor2_pulse_on_cnt[20]} {DiCoupler_top/sensor2_pulse_on_cnt[21]} {DiCoupler_top/sensor2_pulse_on_cnt[22]} {DiCoupler_top/sensor2_pulse_on_cnt[23]} {DiCoupler_top/sensor2_pulse_on_cnt[24]} {DiCoupler_top/sensor2_pulse_on_cnt[25]} {DiCoupler_top/sensor2_pulse_on_cnt[26]} {DiCoupler_top/sensor2_pulse_on_cnt[27]} {DiCoupler_top/sensor2_pulse_on_cnt[28]} {DiCoupler_top/sensor2_pulse_on_cnt[29]} {DiCoupler_top/sensor2_pulse_on_cnt[30]} {DiCoupler_top/sensor2_pulse_on_cnt[31]} {DiCoupler_top/sensor2_pulse_on_cnt[32]} {DiCoupler_top/sensor2_pulse_on_cnt[33]} {DiCoupler_top/sensor2_pulse_on_cnt[34]} {DiCoupler_top/sensor2_pulse_on_cnt[35]}]]
connect_debug_port u_ila_0/probe79 [get_nets [list {DiCoupler_top/sensor2_keep_dly[0]} {DiCoupler_top/sensor2_keep_dly[1]} {DiCoupler_top/sensor2_keep_dly[2]} {DiCoupler_top/sensor2_keep_dly[3]} {DiCoupler_top/sensor2_keep_dly[4]} {DiCoupler_top/sensor2_keep_dly[5]} {DiCoupler_top/sensor2_keep_dly[6]} {DiCoupler_top/sensor2_keep_dly[7]} {DiCoupler_top/sensor2_keep_dly[8]} {DiCoupler_top/sensor2_keep_dly[9]} {DiCoupler_top/sensor2_keep_dly[10]} {DiCoupler_top/sensor2_keep_dly[11]} {DiCoupler_top/sensor2_keep_dly[12]} {DiCoupler_top/sensor2_keep_dly[13]} {DiCoupler_top/sensor2_keep_dly[14]} {DiCoupler_top/sensor2_keep_dly[15]} {DiCoupler_top/sensor2_keep_dly[16]} {DiCoupler_top/sensor2_keep_dly[17]} {DiCoupler_top/sensor2_keep_dly[18]} {DiCoupler_top/sensor2_keep_dly[19]} {DiCoupler_top/sensor2_keep_dly[20]} {DiCoupler_top/sensor2_keep_dly[21]} {DiCoupler_top/sensor2_keep_dly[22]} {DiCoupler_top/sensor2_keep_dly[23]} {DiCoupler_top/sensor2_keep_dly[24]} {DiCoupler_top/sensor2_keep_dly[25]} {DiCoupler_top/sensor2_keep_dly[26]} {DiCoupler_top/sensor2_keep_dly[27]} {DiCoupler_top/sensor2_keep_dly[28]} {DiCoupler_top/sensor2_keep_dly[29]} {DiCoupler_top/sensor2_keep_dly[30]} {DiCoupler_top/sensor2_keep_dly[31]} {DiCoupler_top/sensor2_keep_dly[32]} {DiCoupler_top/sensor2_keep_dly[33]} {DiCoupler_top/sensor2_keep_dly[34]} {DiCoupler_top/sensor2_keep_dly[35]}]]
connect_debug_port u_ila_0/probe84 [get_nets [list {DiCoupler_top/sensor0_keep_dly[0]} {DiCoupler_top/sensor0_keep_dly[1]} {DiCoupler_top/sensor0_keep_dly[2]} {DiCoupler_top/sensor0_keep_dly[3]} {DiCoupler_top/sensor0_keep_dly[4]} {DiCoupler_top/sensor0_keep_dly[5]} {DiCoupler_top/sensor0_keep_dly[6]} {DiCoupler_top/sensor0_keep_dly[7]} {DiCoupler_top/sensor0_keep_dly[8]} {DiCoupler_top/sensor0_keep_dly[9]} {DiCoupler_top/sensor0_keep_dly[10]} {DiCoupler_top/sensor0_keep_dly[11]} {DiCoupler_top/sensor0_keep_dly[12]} {DiCoupler_top/sensor0_keep_dly[13]} {DiCoupler_top/sensor0_keep_dly[14]} {DiCoupler_top/sensor0_keep_dly[15]} {DiCoupler_top/sensor0_keep_dly[16]} {DiCoupler_top/sensor0_keep_dly[17]} {DiCoupler_top/sensor0_keep_dly[18]} {DiCoupler_top/sensor0_keep_dly[19]} {DiCoupler_top/sensor0_keep_dly[20]} {DiCoupler_top/sensor0_keep_dly[21]} {DiCoupler_top/sensor0_keep_dly[22]} {DiCoupler_top/sensor0_keep_dly[23]} {DiCoupler_top/sensor0_keep_dly[24]} {DiCoupler_top/sensor0_keep_dly[25]} {DiCoupler_top/sensor0_keep_dly[26]} {DiCoupler_top/sensor0_keep_dly[27]} {DiCoupler_top/sensor0_keep_dly[28]} {DiCoupler_top/sensor0_keep_dly[29]} {DiCoupler_top/sensor0_keep_dly[30]} {DiCoupler_top/sensor0_keep_dly[31]} {DiCoupler_top/sensor0_keep_dly[32]} {DiCoupler_top/sensor0_keep_dly[33]} {DiCoupler_top/sensor0_keep_dly[34]} {DiCoupler_top/sensor0_keep_dly[35]}]]
connect_debug_port u_ila_0/probe85 [get_nets [list {DiCoupler_top/w_pulse_gap2[0]} {DiCoupler_top/w_pulse_gap2[1]} {DiCoupler_top/w_pulse_gap2[2]} {DiCoupler_top/w_pulse_gap2[3]} {DiCoupler_top/w_pulse_gap2[4]} {DiCoupler_top/w_pulse_gap2[5]} {DiCoupler_top/w_pulse_gap2[6]} {DiCoupler_top/w_pulse_gap2[7]} {DiCoupler_top/w_pulse_gap2[8]} {DiCoupler_top/w_pulse_gap2[9]} {DiCoupler_top/w_pulse_gap2[10]} {DiCoupler_top/w_pulse_gap2[11]} {DiCoupler_top/w_pulse_gap2[12]} {DiCoupler_top/w_pulse_gap2[13]} {DiCoupler_top/w_pulse_gap2[14]} {DiCoupler_top/w_pulse_gap2[15]}]]
connect_debug_port u_ila_0/probe89 [get_nets [list DiCoupler_top/CW_MODE0]]
connect_debug_port u_ila_0/probe90 [get_nets [list DiCoupler_top/CW_MODE2]]
connect_debug_port u_ila_0/probe94 [get_nets [list DiCoupler_top/open_status2]]
connect_debug_port u_ila_0/probe95 [get_nets [list DiCoupler_top/power_status0]]
connect_debug_port u_ila_0/probe96 [get_nets [list DiCoupler_top/power_status2]]
connect_debug_port u_ila_0/probe99 [get_nets [list DiCoupler_top/PW_MODE0]]
connect_debug_port u_ila_0/probe100 [get_nets [list DiCoupler_top/PW_MODE2]]
connect_debug_port u_ila_0/probe102 [get_nets [list DiCoupler_top/r_decor_pulse_pos]]
connect_debug_port u_ila_0/probe103 [get_nets [list DiCoupler_top/sensor0_avg_keep]]
connect_debug_port u_ila_0/probe105 [get_nets [list DiCoupler_top/sensor0_power_rise]]
connect_debug_port u_ila_0/probe106 [get_nets [list DiCoupler_top/sensor2_avg_keep]]
connect_debug_port u_ila_0/probe108 [get_nets [list DiCoupler_top/sensor2_power_rise]]
connect_debug_port u_ila_0/probe109 [get_nets [list DiCoupler_top/w_Z_pulse0_pwm]]
connect_debug_port u_ila_0/probe110 [get_nets [list DiCoupler_top/w_Z_pulse2_pwm]]
connect_debug_port u_ila_1/probe9 [get_nets [list DiCoupler_top/adc0_ch0_lpf_vld]]
connect_debug_port u_ila_1/probe11 [get_nets [list DiCoupler_top/adc0_ch2_lpf_vld]]
connect_debug_port u_ila_1/probe13 [get_nets [list DiCoupler_top/adc1_ch0_lpf_vld]]
connect_debug_port u_ila_1/probe15 [get_nets [list DiCoupler_top/adc1_ch2_lpf_vld]]


set_property OFFCHIP_TERM NONE [get_ports SPI_SDO]
set_property OFFCHIP_TERM NONE [get_ports o_adc0_clka]
set_property OFFCHIP_TERM NONE [get_ports o_adc0_clkb]
set_property OFFCHIP_TERM NONE [get_ports o_adc3_clka]
set_property OFFCHIP_TERM NONE [get_ports o_adc3_clkb]
set_property OFFCHIP_TERM NONE [get_ports o_adc4_clka]
set_property OFFCHIP_TERM NONE [get_ports o_adc4_clkb]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_0/inst/clk_50m]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[0]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[1]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[2]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[3]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[4]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[5]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[6]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[7]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[8]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[9]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[10]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[11]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[12]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[13]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[14]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[15]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[16]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[17]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[18]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[19]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[20]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[21]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[22]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[23]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[24]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[25]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[26]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[27]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[28]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[29]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[30]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_KEEP_NUM[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[0]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[1]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[2]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[3]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[4]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[5]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[6]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[7]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[8]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[9]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[10]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[11]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[12]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[13]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[14]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[15]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[16]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[17]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[18]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[19]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[20]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[21]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[22]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[23]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[24]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[25]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[26]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[27]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[28]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[29]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[30]} {DiCoupler_top/RF_MODE_SENOR_LF/OFF_NUM[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[0]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[1]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[2]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[3]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[4]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[5]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[6]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[7]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[8]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[9]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[10]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[11]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[12]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[13]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[14]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[15]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[16]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[17]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[18]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[19]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[20]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[21]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[22]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[23]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[24]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[25]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[26]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[27]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[28]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[29]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[30]} {DiCoupler_top/RF_MODE_SENOR_LF/ON_KEEP_NUM[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[0]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[1]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[2]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[3]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[4]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[5]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[6]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[7]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[8]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[9]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[10]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[11]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[12]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[13]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[14]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[15]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[16]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[17]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[18]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[19]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[20]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[21]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[22]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[23]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[24]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[25]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[26]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[27]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[28]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[29]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[30]} {DiCoupler_top/RF_MODE_SENOR_LF/on_cnt[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[0]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[1]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[2]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[3]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[4]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[5]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[6]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[7]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[8]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[9]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[10]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[11]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[12]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[13]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[14]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[15]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[16]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[17]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[18]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[19]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[20]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[21]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[22]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[23]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[24]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[25]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[26]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[27]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[28]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[29]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[30]} {DiCoupler_top/RF_MODE_SENOR_LF/p_1_in[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[0]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[1]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[2]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[3]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[4]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[5]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[6]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[7]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[8]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[9]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[10]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[11]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[12]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[13]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[14]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[15]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[16]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[17]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[18]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[19]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[20]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[21]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[22]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[23]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[24]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[25]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[26]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[27]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[28]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[29]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[30]} {DiCoupler_top/RF_MODE_SENOR_LF/off_cnt[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[0]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[1]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[2]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[3]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[4]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[5]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[6]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[7]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[8]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[9]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[10]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[11]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[12]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[13]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[14]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[15]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[16]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[17]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[18]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[19]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[20]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[21]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[22]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[23]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[24]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[25]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[26]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[27]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[28]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[29]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[30]} {DiCoupler_top/RF_MODE_SENOR_LF/power_threshold[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 12 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {DiCoupler_top/AD9238_CH2_CHA[0]} {DiCoupler_top/AD9238_CH2_CHA[1]} {DiCoupler_top/AD9238_CH2_CHA[2]} {DiCoupler_top/AD9238_CH2_CHA[3]} {DiCoupler_top/AD9238_CH2_CHA[4]} {DiCoupler_top/AD9238_CH2_CHA[5]} {DiCoupler_top/AD9238_CH2_CHA[6]} {DiCoupler_top/AD9238_CH2_CHA[7]} {DiCoupler_top/AD9238_CH2_CHA[8]} {DiCoupler_top/AD9238_CH2_CHA[9]} {DiCoupler_top/AD9238_CH2_CHA[10]} {DiCoupler_top/AD9238_CH2_CHA[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 12 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {DiCoupler_top/AD9238_CH0_CHA[0]} {DiCoupler_top/AD9238_CH0_CHA[1]} {DiCoupler_top/AD9238_CH0_CHA[2]} {DiCoupler_top/AD9238_CH0_CHA[3]} {DiCoupler_top/AD9238_CH0_CHA[4]} {DiCoupler_top/AD9238_CH0_CHA[5]} {DiCoupler_top/AD9238_CH0_CHA[6]} {DiCoupler_top/AD9238_CH0_CHA[7]} {DiCoupler_top/AD9238_CH0_CHA[8]} {DiCoupler_top/AD9238_CH0_CHA[9]} {DiCoupler_top/AD9238_CH0_CHA[10]} {DiCoupler_top/AD9238_CH0_CHA[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 12 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {DiCoupler_top/AD9238_CH0_CHB[0]} {DiCoupler_top/AD9238_CH0_CHB[1]} {DiCoupler_top/AD9238_CH0_CHB[2]} {DiCoupler_top/AD9238_CH0_CHB[3]} {DiCoupler_top/AD9238_CH0_CHB[4]} {DiCoupler_top/AD9238_CH0_CHB[5]} {DiCoupler_top/AD9238_CH0_CHB[6]} {DiCoupler_top/AD9238_CH0_CHB[7]} {DiCoupler_top/AD9238_CH0_CHB[8]} {DiCoupler_top/AD9238_CH0_CHB[9]} {DiCoupler_top/AD9238_CH0_CHB[10]} {DiCoupler_top/AD9238_CH0_CHB[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 12 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {DiCoupler_top/AD9238_CH2_CHB[0]} {DiCoupler_top/AD9238_CH2_CHB[1]} {DiCoupler_top/AD9238_CH2_CHB[2]} {DiCoupler_top/AD9238_CH2_CHB[3]} {DiCoupler_top/AD9238_CH2_CHB[4]} {DiCoupler_top/AD9238_CH2_CHB[5]} {DiCoupler_top/AD9238_CH2_CHB[6]} {DiCoupler_top/AD9238_CH2_CHB[7]} {DiCoupler_top/AD9238_CH2_CHB[8]} {DiCoupler_top/AD9238_CH2_CHB[9]} {DiCoupler_top/AD9238_CH2_CHB[10]} {DiCoupler_top/AD9238_CH2_CHB[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {DiCoupler_top/JX_DOUT2[0]} {DiCoupler_top/JX_DOUT2[1]} {DiCoupler_top/JX_DOUT2[2]} {DiCoupler_top/JX_DOUT2[3]} {DiCoupler_top/JX_DOUT2[4]} {DiCoupler_top/JX_DOUT2[5]} {DiCoupler_top/JX_DOUT2[6]} {DiCoupler_top/JX_DOUT2[7]} {DiCoupler_top/JX_DOUT2[8]} {DiCoupler_top/JX_DOUT2[9]} {DiCoupler_top/JX_DOUT2[10]} {DiCoupler_top/JX_DOUT2[11]} {DiCoupler_top/JX_DOUT2[12]} {DiCoupler_top/JX_DOUT2[13]} {DiCoupler_top/JX_DOUT2[14]} {DiCoupler_top/JX_DOUT2[15]} {DiCoupler_top/JX_DOUT2[16]} {DiCoupler_top/JX_DOUT2[17]} {DiCoupler_top/JX_DOUT2[18]} {DiCoupler_top/JX_DOUT2[19]} {DiCoupler_top/JX_DOUT2[20]} {DiCoupler_top/JX_DOUT2[21]} {DiCoupler_top/JX_DOUT2[22]} {DiCoupler_top/JX_DOUT2[23]} {DiCoupler_top/JX_DOUT2[24]} {DiCoupler_top/JX_DOUT2[25]} {DiCoupler_top/JX_DOUT2[26]} {DiCoupler_top/JX_DOUT2[27]} {DiCoupler_top/JX_DOUT2[28]} {DiCoupler_top/JX_DOUT2[29]} {DiCoupler_top/JX_DOUT2[30]} {DiCoupler_top/JX_DOUT2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {DiCoupler_top/JX2_result[0]} {DiCoupler_top/JX2_result[1]} {DiCoupler_top/JX2_result[2]} {DiCoupler_top/JX2_result[3]} {DiCoupler_top/JX2_result[4]} {DiCoupler_top/JX2_result[5]} {DiCoupler_top/JX2_result[6]} {DiCoupler_top/JX2_result[7]} {DiCoupler_top/JX2_result[8]} {DiCoupler_top/JX2_result[9]} {DiCoupler_top/JX2_result[10]} {DiCoupler_top/JX2_result[11]} {DiCoupler_top/JX2_result[12]} {DiCoupler_top/JX2_result[13]} {DiCoupler_top/JX2_result[14]} {DiCoupler_top/JX2_result[15]} {DiCoupler_top/JX2_result[16]} {DiCoupler_top/JX2_result[17]} {DiCoupler_top/JX2_result[18]} {DiCoupler_top/JX2_result[19]} {DiCoupler_top/JX2_result[20]} {DiCoupler_top/JX2_result[21]} {DiCoupler_top/JX2_result[22]} {DiCoupler_top/JX2_result[23]} {DiCoupler_top/JX2_result[24]} {DiCoupler_top/JX2_result[25]} {DiCoupler_top/JX2_result[26]} {DiCoupler_top/JX2_result[27]} {DiCoupler_top/JX2_result[28]} {DiCoupler_top/JX2_result[29]} {DiCoupler_top/JX2_result[30]} {DiCoupler_top/JX2_result[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {DiCoupler_top/INPUT_SENSOR1_JX_AVG[0]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[1]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[2]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[3]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[4]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[5]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[6]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[7]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[8]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[9]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[10]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[11]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[12]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[13]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[14]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[15]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[16]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[17]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[18]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[19]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[20]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[21]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[22]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[23]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[24]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[25]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[26]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[27]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[28]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[29]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[30]} {DiCoupler_top/INPUT_SENSOR1_JX_AVG[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {DiCoupler_top/INPUT_SENSOR1_R_AVG[0]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[1]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[2]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[3]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[4]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[5]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[6]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[7]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[8]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[9]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[10]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[11]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[12]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[13]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[14]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[15]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[16]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[17]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[18]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[19]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[20]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[21]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[22]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[23]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[24]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[25]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[26]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[27]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[28]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[29]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[30]} {DiCoupler_top/INPUT_SENSOR1_R_AVG[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {DiCoupler_top/OFF_KEEP_NUM[0]} {DiCoupler_top/OFF_KEEP_NUM[1]} {DiCoupler_top/OFF_KEEP_NUM[2]} {DiCoupler_top/OFF_KEEP_NUM[3]} {DiCoupler_top/OFF_KEEP_NUM[4]} {DiCoupler_top/OFF_KEEP_NUM[5]} {DiCoupler_top/OFF_KEEP_NUM[6]} {DiCoupler_top/OFF_KEEP_NUM[7]} {DiCoupler_top/OFF_KEEP_NUM[8]} {DiCoupler_top/OFF_KEEP_NUM[9]} {DiCoupler_top/OFF_KEEP_NUM[10]} {DiCoupler_top/OFF_KEEP_NUM[11]} {DiCoupler_top/OFF_KEEP_NUM[12]} {DiCoupler_top/OFF_KEEP_NUM[13]} {DiCoupler_top/OFF_KEEP_NUM[14]} {DiCoupler_top/OFF_KEEP_NUM[15]} {DiCoupler_top/OFF_KEEP_NUM[16]} {DiCoupler_top/OFF_KEEP_NUM[17]} {DiCoupler_top/OFF_KEEP_NUM[18]} {DiCoupler_top/OFF_KEEP_NUM[19]} {DiCoupler_top/OFF_KEEP_NUM[20]} {DiCoupler_top/OFF_KEEP_NUM[21]} {DiCoupler_top/OFF_KEEP_NUM[22]} {DiCoupler_top/OFF_KEEP_NUM[23]} {DiCoupler_top/OFF_KEEP_NUM[24]} {DiCoupler_top/OFF_KEEP_NUM[25]} {DiCoupler_top/OFF_KEEP_NUM[26]} {DiCoupler_top/OFF_KEEP_NUM[27]} {DiCoupler_top/OFF_KEEP_NUM[28]} {DiCoupler_top/OFF_KEEP_NUM[29]} {DiCoupler_top/OFF_KEEP_NUM[30]} {DiCoupler_top/OFF_KEEP_NUM[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {DiCoupler_top/ON_KEEP_NUM[0]} {DiCoupler_top/ON_KEEP_NUM[1]} {DiCoupler_top/ON_KEEP_NUM[2]} {DiCoupler_top/ON_KEEP_NUM[3]} {DiCoupler_top/ON_KEEP_NUM[4]} {DiCoupler_top/ON_KEEP_NUM[5]} {DiCoupler_top/ON_KEEP_NUM[6]} {DiCoupler_top/ON_KEEP_NUM[7]} {DiCoupler_top/ON_KEEP_NUM[8]} {DiCoupler_top/ON_KEEP_NUM[9]} {DiCoupler_top/ON_KEEP_NUM[10]} {DiCoupler_top/ON_KEEP_NUM[11]} {DiCoupler_top/ON_KEEP_NUM[12]} {DiCoupler_top/ON_KEEP_NUM[13]} {DiCoupler_top/ON_KEEP_NUM[14]} {DiCoupler_top/ON_KEEP_NUM[15]} {DiCoupler_top/ON_KEEP_NUM[16]} {DiCoupler_top/ON_KEEP_NUM[17]} {DiCoupler_top/ON_KEEP_NUM[18]} {DiCoupler_top/ON_KEEP_NUM[19]} {DiCoupler_top/ON_KEEP_NUM[20]} {DiCoupler_top/ON_KEEP_NUM[21]} {DiCoupler_top/ON_KEEP_NUM[22]} {DiCoupler_top/ON_KEEP_NUM[23]} {DiCoupler_top/ON_KEEP_NUM[24]} {DiCoupler_top/ON_KEEP_NUM[25]} {DiCoupler_top/ON_KEEP_NUM[26]} {DiCoupler_top/ON_KEEP_NUM[27]} {DiCoupler_top/ON_KEEP_NUM[28]} {DiCoupler_top/ON_KEEP_NUM[29]} {DiCoupler_top/ON_KEEP_NUM[30]} {DiCoupler_top/ON_KEEP_NUM[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {DiCoupler_top/OFF_NUM2[0]} {DiCoupler_top/OFF_NUM2[1]} {DiCoupler_top/OFF_NUM2[2]} {DiCoupler_top/OFF_NUM2[3]} {DiCoupler_top/OFF_NUM2[4]} {DiCoupler_top/OFF_NUM2[5]} {DiCoupler_top/OFF_NUM2[6]} {DiCoupler_top/OFF_NUM2[7]} {DiCoupler_top/OFF_NUM2[8]} {DiCoupler_top/OFF_NUM2[9]} {DiCoupler_top/OFF_NUM2[10]} {DiCoupler_top/OFF_NUM2[11]} {DiCoupler_top/OFF_NUM2[12]} {DiCoupler_top/OFF_NUM2[13]} {DiCoupler_top/OFF_NUM2[14]} {DiCoupler_top/OFF_NUM2[15]} {DiCoupler_top/OFF_NUM2[16]} {DiCoupler_top/OFF_NUM2[17]} {DiCoupler_top/OFF_NUM2[18]} {DiCoupler_top/OFF_NUM2[19]} {DiCoupler_top/OFF_NUM2[20]} {DiCoupler_top/OFF_NUM2[21]} {DiCoupler_top/OFF_NUM2[22]} {DiCoupler_top/OFF_NUM2[23]} {DiCoupler_top/OFF_NUM2[24]} {DiCoupler_top/OFF_NUM2[25]} {DiCoupler_top/OFF_NUM2[26]} {DiCoupler_top/OFF_NUM2[27]} {DiCoupler_top/OFF_NUM2[28]} {DiCoupler_top/OFF_NUM2[29]} {DiCoupler_top/OFF_NUM2[30]} {DiCoupler_top/OFF_NUM2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 32 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {DiCoupler_top/R2_result[0]} {DiCoupler_top/R2_result[1]} {DiCoupler_top/R2_result[2]} {DiCoupler_top/R2_result[3]} {DiCoupler_top/R2_result[4]} {DiCoupler_top/R2_result[5]} {DiCoupler_top/R2_result[6]} {DiCoupler_top/R2_result[7]} {DiCoupler_top/R2_result[8]} {DiCoupler_top/R2_result[9]} {DiCoupler_top/R2_result[10]} {DiCoupler_top/R2_result[11]} {DiCoupler_top/R2_result[12]} {DiCoupler_top/R2_result[13]} {DiCoupler_top/R2_result[14]} {DiCoupler_top/R2_result[15]} {DiCoupler_top/R2_result[16]} {DiCoupler_top/R2_result[17]} {DiCoupler_top/R2_result[18]} {DiCoupler_top/R2_result[19]} {DiCoupler_top/R2_result[20]} {DiCoupler_top/R2_result[21]} {DiCoupler_top/R2_result[22]} {DiCoupler_top/R2_result[23]} {DiCoupler_top/R2_result[24]} {DiCoupler_top/R2_result[25]} {DiCoupler_top/R2_result[26]} {DiCoupler_top/R2_result[27]} {DiCoupler_top/R2_result[28]} {DiCoupler_top/R2_result[29]} {DiCoupler_top/R2_result[30]} {DiCoupler_top/R2_result[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 32 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {DiCoupler_top/R_DOUT2[0]} {DiCoupler_top/R_DOUT2[1]} {DiCoupler_top/R_DOUT2[2]} {DiCoupler_top/R_DOUT2[3]} {DiCoupler_top/R_DOUT2[4]} {DiCoupler_top/R_DOUT2[5]} {DiCoupler_top/R_DOUT2[6]} {DiCoupler_top/R_DOUT2[7]} {DiCoupler_top/R_DOUT2[8]} {DiCoupler_top/R_DOUT2[9]} {DiCoupler_top/R_DOUT2[10]} {DiCoupler_top/R_DOUT2[11]} {DiCoupler_top/R_DOUT2[12]} {DiCoupler_top/R_DOUT2[13]} {DiCoupler_top/R_DOUT2[14]} {DiCoupler_top/R_DOUT2[15]} {DiCoupler_top/R_DOUT2[16]} {DiCoupler_top/R_DOUT2[17]} {DiCoupler_top/R_DOUT2[18]} {DiCoupler_top/R_DOUT2[19]} {DiCoupler_top/R_DOUT2[20]} {DiCoupler_top/R_DOUT2[21]} {DiCoupler_top/R_DOUT2[22]} {DiCoupler_top/R_DOUT2[23]} {DiCoupler_top/R_DOUT2[24]} {DiCoupler_top/R_DOUT2[25]} {DiCoupler_top/R_DOUT2[26]} {DiCoupler_top/R_DOUT2[27]} {DiCoupler_top/R_DOUT2[28]} {DiCoupler_top/R_DOUT2[29]} {DiCoupler_top/R_DOUT2[30]} {DiCoupler_top/R_DOUT2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 16 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {DiCoupler_top/VF_POWER2_FILTER[0]} {DiCoupler_top/VF_POWER2_FILTER[1]} {DiCoupler_top/VF_POWER2_FILTER[2]} {DiCoupler_top/VF_POWER2_FILTER[3]} {DiCoupler_top/VF_POWER2_FILTER[4]} {DiCoupler_top/VF_POWER2_FILTER[5]} {DiCoupler_top/VF_POWER2_FILTER[6]} {DiCoupler_top/VF_POWER2_FILTER[7]} {DiCoupler_top/VF_POWER2_FILTER[8]} {DiCoupler_top/VF_POWER2_FILTER[9]} {DiCoupler_top/VF_POWER2_FILTER[10]} {DiCoupler_top/VF_POWER2_FILTER[11]} {DiCoupler_top/VF_POWER2_FILTER[12]} {DiCoupler_top/VF_POWER2_FILTER[13]} {DiCoupler_top/VF_POWER2_FILTER[14]} {DiCoupler_top/VF_POWER2_FILTER[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 32 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {DiCoupler_top/demod_freq_coef2[0]} {DiCoupler_top/demod_freq_coef2[1]} {DiCoupler_top/demod_freq_coef2[2]} {DiCoupler_top/demod_freq_coef2[3]} {DiCoupler_top/demod_freq_coef2[4]} {DiCoupler_top/demod_freq_coef2[5]} {DiCoupler_top/demod_freq_coef2[6]} {DiCoupler_top/demod_freq_coef2[7]} {DiCoupler_top/demod_freq_coef2[8]} {DiCoupler_top/demod_freq_coef2[9]} {DiCoupler_top/demod_freq_coef2[10]} {DiCoupler_top/demod_freq_coef2[11]} {DiCoupler_top/demod_freq_coef2[12]} {DiCoupler_top/demod_freq_coef2[13]} {DiCoupler_top/demod_freq_coef2[14]} {DiCoupler_top/demod_freq_coef2[15]} {DiCoupler_top/demod_freq_coef2[16]} {DiCoupler_top/demod_freq_coef2[17]} {DiCoupler_top/demod_freq_coef2[18]} {DiCoupler_top/demod_freq_coef2[19]} {DiCoupler_top/demod_freq_coef2[20]} {DiCoupler_top/demod_freq_coef2[21]} {DiCoupler_top/demod_freq_coef2[22]} {DiCoupler_top/demod_freq_coef2[23]} {DiCoupler_top/demod_freq_coef2[24]} {DiCoupler_top/demod_freq_coef2[25]} {DiCoupler_top/demod_freq_coef2[26]} {DiCoupler_top/demod_freq_coef2[27]} {DiCoupler_top/demod_freq_coef2[28]} {DiCoupler_top/demod_freq_coef2[29]} {DiCoupler_top/demod_freq_coef2[30]} {DiCoupler_top/demod_freq_coef2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list DiCoupler_top/AD9238_CH0_vld]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list DiCoupler_top/AD9238_CH2_vld]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/CW_MODE]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/down_threshold]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/power_status]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/pulse_ok]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/PW_MODE]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/pwm_on]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list DiCoupler_top/RF_MODE_SENOR_LF/rst]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50m]
