







set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc0_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc1_data1[0]}]


create_clock -period 10.000 -name sysclk_p -waveform {0.000 5.000} [get_ports i_sys_clk_p]
set_property PACKAGE_PIN D9 [get_ports i_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL135 [get_ports i_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL135 [get_ports i_sys_clk_n]


set_property IOSTANDARD LVCMOS33 [get_ports o_adc0_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc0_clkb]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SDI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SDO]
set_property PACKAGE_PIN AD18 [get_ports SPI_CS]
set_property PACKAGE_PIN AC19 [get_ports SPI_SCLK]
set_property PACKAGE_PIN AD19 [get_ports SPI_SDI]
set_property PACKAGE_PIN AC18 [get_ports SPI_SDO]

set_property PACKAGE_PIN AK22 [get_ports o_adc0_clka]
set_property PACKAGE_PIN AJ25 [get_ports o_adc0_clkb]
set_property PACKAGE_PIN AD21 [get_ports {i_adc0_data0[0]}]
set_property PACKAGE_PIN AC23 [get_ports {i_adc0_data0[1]}]
set_property PACKAGE_PIN AC22 [get_ports {i_adc0_data0[2]}]
set_property PACKAGE_PIN AG25 [get_ports {i_adc0_data0[3]}]
set_property PACKAGE_PIN AG24 [get_ports {i_adc0_data0[4]}]
set_property PACKAGE_PIN AF24 [get_ports {i_adc0_data0[5]}]
set_property PACKAGE_PIN AF23 [get_ports {i_adc0_data0[6]}]
set_property PACKAGE_PIN AE23 [get_ports {i_adc0_data0[7]}]
set_property PACKAGE_PIN AD23 [get_ports {i_adc0_data0[8]}]
set_property PACKAGE_PIN AD24 [get_ports {i_adc0_data0[9]}]
set_property PACKAGE_PIN AC24 [get_ports {i_adc0_data0[10]}]
set_property PACKAGE_PIN AK23 [get_ports {i_adc0_data0[11]}]
set_property PACKAGE_PIN AH19 [get_ports {i_adc0_data1[0]}]
set_property PACKAGE_PIN AK18 [get_ports {i_adc0_data1[1]}]
set_property PACKAGE_PIN AK17 [get_ports {i_adc0_data1[2]}]
set_property PACKAGE_PIN AH21 [get_ports {i_adc0_data1[3]}]
set_property PACKAGE_PIN AG21 [get_ports {i_adc0_data1[4]}]
set_property PACKAGE_PIN AH22 [get_ports {i_adc0_data1[5]}]
set_property PACKAGE_PIN AG22 [get_ports {i_adc0_data1[6]}]
set_property PACKAGE_PIN AH24 [get_ports {i_adc0_data1[7]}]
set_property PACKAGE_PIN AH23 [get_ports {i_adc0_data1[8]}]
set_property PACKAGE_PIN AJ24 [get_ports {i_adc0_data1[9]}]
set_property PACKAGE_PIN AJ23 [get_ports {i_adc0_data1[10]}]
set_property PACKAGE_PIN AK25 [get_ports {i_adc0_data1[11]}]

set_property PACKAGE_PIN P23 [get_ports {MOTO_DIR[0]}]
set_property PACKAGE_PIN P24 [get_ports {MOTO_PWM[0]}]
set_property PACKAGE_PIN R22 [get_ports {MOTO_DIR[1]}]
set_property PACKAGE_PIN R23 [get_ports {MOTO_PWM[1]}]
set_property PACKAGE_PIN T22 [get_ports {MOTO_DIR[2]}]
set_property PACKAGE_PIN T23 [get_ports {MOTO_PWM[2]}]
set_property PACKAGE_PIN P25 [get_ports {MOTO_DIR[3]}]
set_property PACKAGE_PIN P26 [get_ports {MOTO_PWM[3]}]
set_property PACKAGE_PIN U25 [get_ports {MOTO_DIR[4]}]
set_property PACKAGE_PIN V26 [get_ports {MOTO_PWM[4]}]
set_property PACKAGE_PIN V23 [get_ports {MOTO_DIR[5]}]
set_property PACKAGE_PIN W24 [get_ports {MOTO_PWM[5]}]
set_property PACKAGE_PIN W25 [get_ports {MOTO_DIR[6]}]
set_property PACKAGE_PIN W26 [get_ports {MOTO_PWM[6]}]
set_property PACKAGE_PIN P21 [get_ports {MOTO_DIR[7]}]
set_property PACKAGE_PIN R21 [get_ports {MOTO_PWM[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_DIR[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_PWM[0]}]

set_property PACKAGE_PIN T28 [get_ports {MOTO_EN[0]}]
set_property PACKAGE_PIN P28 [get_ports {MOTO_EN[1]}]
set_property PACKAGE_PIN U30 [get_ports {MOTO_EN[2]}]
set_property PACKAGE_PIN N27 [get_ports {MOTO_EN[3]}]
set_property PACKAGE_PIN R30 [get_ports {MOTO_EN[4]}]
set_property PACKAGE_PIN P29 [get_ports {MOTO_EN[5]}]
set_property PACKAGE_PIN R26 [get_ports {MOTO_EN[6]}]
set_property PACKAGE_PIN V24 [get_ports {MOTO_EN[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_EN[7]}]

set_property PACKAGE_PIN R28 [get_ports {MOTO_ALM[0]}]
set_property PACKAGE_PIN N28 [get_ports {MOTO_ALM[1]}]
set_property PACKAGE_PIN T30 [get_ports {MOTO_ALM[2]}]
set_property PACKAGE_PIN N26 [get_ports {MOTO_ALM[3]}]
set_property PACKAGE_PIN P30 [get_ports {MOTO_ALM[4]}]
set_property PACKAGE_PIN N29 [get_ports {MOTO_ALM[5]}]
set_property PACKAGE_PIN R25 [get_ports {MOTO_ALM[6]}]
set_property PACKAGE_PIN U24 [get_ports {MOTO_ALM[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MOTO_ALM[0]}]

set_property PACKAGE_PIN AG17 [get_ports {debug_led[0]}]
set_property PACKAGE_PIN AG16 [get_ports {debug_led[1]}]
set_property PACKAGE_PIN AF15 [get_ports {debug_led[2]}]
set_property PACKAGE_PIN AG15 [get_ports {debug_led[3]}]
set_property PACKAGE_PIN AF14 [get_ports {debug_led[4]}]
set_property PACKAGE_PIN AG14 [get_ports {debug_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_led[0]}]










set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data0[0]}]
set_property PACKAGE_PIN AJ21 [get_ports {i_adc3_data0[11]}]
set_property PACKAGE_PIN AK21 [get_ports {i_adc3_data0[10]}]
set_property PACKAGE_PIN AJ20 [get_ports {i_adc3_data0[9]}]
set_property PACKAGE_PIN AK20 [get_ports {i_adc3_data0[8]}]
set_property PACKAGE_PIN AF20 [get_ports {i_adc3_data0[7]}]
set_property PACKAGE_PIN AG20 [get_ports {i_adc3_data0[6]}]
set_property PACKAGE_PIN AA22 [get_ports {i_adc3_data0[5]}]
set_property PACKAGE_PIN AA23 [get_ports {i_adc3_data0[4]}]
set_property PACKAGE_PIN AB21 [get_ports {i_adc3_data0[3]}]
set_property PACKAGE_PIN AB22 [get_ports {i_adc3_data0[2]}]
set_property PACKAGE_PIN AD20 [get_ports {i_adc3_data0[1]}]
set_property PACKAGE_PIN AE20 [get_ports {i_adc3_data0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc3_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data1[0]}]
set_property PACKAGE_PIN AA24 [get_ports {i_adc3_data1[11]}]
set_property PACKAGE_PIN AB24 [get_ports {i_adc3_data1[10]}]
set_property PACKAGE_PIN Y22 [get_ports {i_adc3_data1[9]}]
set_property PACKAGE_PIN Y23 [get_ports {i_adc3_data1[8]}]
set_property PACKAGE_PIN W21 [get_ports {i_adc3_data1[7]}]
set_property PACKAGE_PIN Y21 [get_ports {i_adc3_data1[6]}]
set_property PACKAGE_PIN AF19 [get_ports {i_adc3_data1[5]}]
set_property PACKAGE_PIN AG19 [get_ports {i_adc3_data1[4]}]
set_property PACKAGE_PIN Y20 [get_ports {i_adc3_data1[3]}]
set_property PACKAGE_PIN AA20 [get_ports {i_adc3_data1[2]}]
set_property PACKAGE_PIN AB19 [get_ports {i_adc3_data1[1]}]
set_property PACKAGE_PIN AB20 [get_ports {i_adc3_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc4_data0[0]}]
set_property PACKAGE_PIN AB16 [get_ports {i_adc4_data0[11]}]
set_property PACKAGE_PIN AC17 [get_ports {i_adc4_data0[10]}]
set_property PACKAGE_PIN AC16 [get_ports {i_adc4_data0[9]}]
set_property PACKAGE_PIN AA15 [get_ports {i_adc4_data0[8]}]
set_property PACKAGE_PIN AA14 [get_ports {i_adc4_data0[7]}]
set_property PACKAGE_PIN AB15 [get_ports {i_adc4_data0[6]}]
set_property PACKAGE_PIN AB14 [get_ports {i_adc4_data0[5]}]
set_property PACKAGE_PIN AC14 [get_ports {i_adc4_data0[4]}]
set_property PACKAGE_PIN AC13 [get_ports {i_adc4_data0[3]}]
set_property PACKAGE_PIN AB12 [get_ports {i_adc4_data0[2]}]
set_property PACKAGE_PIN AC12 [get_ports {i_adc4_data0[1]}]
set_property PACKAGE_PIN AH18 [get_ports {i_adc4_data0[0]}]
set_property PACKAGE_PIN AE17 [get_ports {i_adc4_data1[11]}]
set_property PACKAGE_PIN AD16 [get_ports {i_adc4_data1[10]}]
set_property PACKAGE_PIN AD15 [get_ports {i_adc4_data1[9]}]
set_property PACKAGE_PIN AE16 [get_ports {i_adc4_data1[8]}]
set_property PACKAGE_PIN AE15 [get_ports {i_adc4_data1[7]}]
set_property PACKAGE_PIN AD14 [get_ports {i_adc4_data1[6]}]
set_property PACKAGE_PIN AD13 [get_ports {i_adc4_data1[5]}]
set_property PACKAGE_PIN AE13 [get_ports {i_adc4_data1[4]}]
set_property PACKAGE_PIN AF13 [get_ports {i_adc4_data1[3]}]
set_property PACKAGE_PIN AE12 [get_ports {i_adc4_data1[2]}]
set_property PACKAGE_PIN AF12 [get_ports {i_adc4_data1[1]}]
set_property PACKAGE_PIN AJ16 [get_ports {i_adc4_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc3_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc3_clkb]
set_property PACKAGE_PIN AE22 [get_ports o_adc3_clka]
set_property PACKAGE_PIN AF22 [get_ports o_adc3_clkb]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc4_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc4_clkb]
set_property PACKAGE_PIN AB17 [get_ports o_adc4_clka]
set_property PACKAGE_PIN AE18 [get_ports o_adc4_clkb]














set_property PACKAGE_PIN AD28 [get_ports {i_adc1_data0[11]}]
set_property PACKAGE_PIN AD25 [get_ports {i_adc1_data0[10]}]
set_property PACKAGE_PIN AE26 [get_ports {i_adc1_data0[9]}]
set_property PACKAGE_PIN AE25 [get_ports {i_adc1_data0[8]}]
set_property PACKAGE_PIN AF25 [get_ports {i_adc1_data0[7]}]
set_property PACKAGE_PIN AG26 [get_ports {i_adc1_data0[6]}]
set_property PACKAGE_PIN AG27 [get_ports {i_adc1_data0[5]}]
set_property PACKAGE_PIN AH26 [get_ports {i_adc1_data0[4]}]
set_property PACKAGE_PIN AH27 [get_ports {i_adc1_data0[3]}]
set_property PACKAGE_PIN AJ26 [get_ports {i_adc1_data0[2]}]
set_property PACKAGE_PIN AK26 [get_ports {i_adc1_data0[1]}]
set_property PACKAGE_PIN AK27 [get_ports {i_adc1_data0[0]}]
set_property PACKAGE_PIN AF28 [get_ports {i_adc1_data1[11]}]
set_property PACKAGE_PIN AD30 [get_ports {i_adc1_data1[10]}]
set_property PACKAGE_PIN AE30 [get_ports {i_adc1_data1[9]}]
set_property PACKAGE_PIN AF30 [get_ports {i_adc1_data1[8]}]
set_property PACKAGE_PIN AG30 [get_ports {i_adc1_data1[7]}]
set_property PACKAGE_PIN AF29 [get_ports {i_adc1_data1[6]}]
set_property PACKAGE_PIN AG29 [get_ports {i_adc1_data1[5]}]
set_property PACKAGE_PIN AH28 [get_ports {i_adc1_data1[4]}]
set_property PACKAGE_PIN AH29 [get_ports {i_adc1_data1[3]}]
set_property PACKAGE_PIN AJ28 [get_ports {i_adc1_data1[2]}]
set_property PACKAGE_PIN AJ29 [get_ports {i_adc1_data1[1]}]
set_property PACKAGE_PIN AJ30 [get_ports {i_adc1_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc1_clka]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc1_clkb]
set_property PACKAGE_PIN AC28 [get_ports o_adc1_clka]
set_property PACKAGE_PIN AE28 [get_ports o_adc1_clkb]



set_property IOSTANDARD LVCMOS33 [get_ports FPGA_T25]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_T24]
set_property PACKAGE_PIN T24 [get_ports FPGA_T24]
set_property PACKAGE_PIN T25 [get_ports FPGA_T25]


set_property OFFCHIP_TERM NONE [get_ports SPI_SDO]
set_property OFFCHIP_TERM NONE [get_ports o_adc0_clka]
set_property OFFCHIP_TERM NONE [get_ports o_adc0_clkb]
set_property OFFCHIP_TERM NONE [get_ports o_adc3_clka]
set_property OFFCHIP_TERM NONE [get_ports o_adc3_clkb]
set_property OFFCHIP_TERM NONE [get_ports o_adc4_clka]
set_property OFFCHIP_TERM NONE [get_ports o_adc4_clkb]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_0/inst/clk_64m]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {DiCoupler_top/AD9238_CH0_CHA[0]} {DiCoupler_top/AD9238_CH0_CHA[1]} {DiCoupler_top/AD9238_CH0_CHA[2]} {DiCoupler_top/AD9238_CH0_CHA[3]} {DiCoupler_top/AD9238_CH0_CHA[4]} {DiCoupler_top/AD9238_CH0_CHA[5]} {DiCoupler_top/AD9238_CH0_CHA[6]} {DiCoupler_top/AD9238_CH0_CHA[7]} {DiCoupler_top/AD9238_CH0_CHA[8]} {DiCoupler_top/AD9238_CH0_CHA[9]} {DiCoupler_top/AD9238_CH0_CHA[10]} {DiCoupler_top/AD9238_CH0_CHA[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 12 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {DiCoupler_top/AD9238_CH2_CHA[0]} {DiCoupler_top/AD9238_CH2_CHA[1]} {DiCoupler_top/AD9238_CH2_CHA[2]} {DiCoupler_top/AD9238_CH2_CHA[3]} {DiCoupler_top/AD9238_CH2_CHA[4]} {DiCoupler_top/AD9238_CH2_CHA[5]} {DiCoupler_top/AD9238_CH2_CHA[6]} {DiCoupler_top/AD9238_CH2_CHA[7]} {DiCoupler_top/AD9238_CH2_CHA[8]} {DiCoupler_top/AD9238_CH2_CHA[9]} {DiCoupler_top/AD9238_CH2_CHA[10]} {DiCoupler_top/AD9238_CH2_CHA[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {DiCoupler_top/AD9238_CH2_CHB[0]} {DiCoupler_top/AD9238_CH2_CHB[1]} {DiCoupler_top/AD9238_CH2_CHB[2]} {DiCoupler_top/AD9238_CH2_CHB[3]} {DiCoupler_top/AD9238_CH2_CHB[4]} {DiCoupler_top/AD9238_CH2_CHB[5]} {DiCoupler_top/AD9238_CH2_CHB[6]} {DiCoupler_top/AD9238_CH2_CHB[7]} {DiCoupler_top/AD9238_CH2_CHB[8]} {DiCoupler_top/AD9238_CH2_CHB[9]} {DiCoupler_top/AD9238_CH2_CHB[10]} {DiCoupler_top/AD9238_CH2_CHB[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {DiCoupler_top/AD9238_CH4_CHA[0]} {DiCoupler_top/AD9238_CH4_CHA[1]} {DiCoupler_top/AD9238_CH4_CHA[2]} {DiCoupler_top/AD9238_CH4_CHA[3]} {DiCoupler_top/AD9238_CH4_CHA[4]} {DiCoupler_top/AD9238_CH4_CHA[5]} {DiCoupler_top/AD9238_CH4_CHA[6]} {DiCoupler_top/AD9238_CH4_CHA[7]} {DiCoupler_top/AD9238_CH4_CHA[8]} {DiCoupler_top/AD9238_CH4_CHA[9]} {DiCoupler_top/AD9238_CH4_CHA[10]} {DiCoupler_top/AD9238_CH4_CHA[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 12 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {DiCoupler_top/AD9238_CH4_CHB[0]} {DiCoupler_top/AD9238_CH4_CHB[1]} {DiCoupler_top/AD9238_CH4_CHB[2]} {DiCoupler_top/AD9238_CH4_CHB[3]} {DiCoupler_top/AD9238_CH4_CHB[4]} {DiCoupler_top/AD9238_CH4_CHB[5]} {DiCoupler_top/AD9238_CH4_CHB[6]} {DiCoupler_top/AD9238_CH4_CHB[7]} {DiCoupler_top/AD9238_CH4_CHB[8]} {DiCoupler_top/AD9238_CH4_CHB[9]} {DiCoupler_top/AD9238_CH4_CHB[10]} {DiCoupler_top/AD9238_CH4_CHB[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 12 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {DiCoupler_top/AD9238_CH0_CHB[0]} {DiCoupler_top/AD9238_CH0_CHB[1]} {DiCoupler_top/AD9238_CH0_CHB[2]} {DiCoupler_top/AD9238_CH0_CHB[3]} {DiCoupler_top/AD9238_CH0_CHB[4]} {DiCoupler_top/AD9238_CH0_CHB[5]} {DiCoupler_top/AD9238_CH0_CHB[6]} {DiCoupler_top/AD9238_CH0_CHB[7]} {DiCoupler_top/AD9238_CH0_CHB[8]} {DiCoupler_top/AD9238_CH0_CHB[9]} {DiCoupler_top/AD9238_CH0_CHB[10]} {DiCoupler_top/AD9238_CH0_CHB[11]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets o_adc4_clkb_OBUF]
